import type { CaseEnvironment } from '../../../simulation/terminal/caseEnvironment';
import { runLocalHttpCommand, type LocalHttpExchange } from '../../../simulation/http/localHttp';
import { runLocalSqlCommand, type LocalSqlTable } from '../../../simulation/data/localSql';
function pick<T>(seed:number,v:T[]):T{return v[Math.abs(seed)%v.length];}
export function createAct2ContractEnvironment(missionId:string,seed:number){
 const home=`/home/ilya/contracts/${missionId}`;const session=`sid_${(seed>>>0).toString(36).slice(0,5)}`;const remote=pick(seed,['203.0.113.19','198.51.100.47','192.0.2.64']);const req=`rq-${100+Math.abs(seed)%700}`;const user=pick(seed+1,['operator-04','courier-19','support-08']);
 const artifact=missionId==='act2-contract-http'?'artifact.act2.http':missionId==='act2-contract-session'?'artifact.act2.session':'artifact.act2.timeline';
 const exchanges:LocalHttpExchange[]=[{id:req,method:'GET',path:'/login/continue',requestHeaders:{Host:'local.contract.lab',Cookie:session,'X-Source-IP':remote},status:302,reason:'Found',responseHeaders:{Location:'/dashboard','X-Request-ID':req},responseBody:'',artifactId:artifact},{id:`${req}-2`,method:'GET',path:'/dashboard',requestHeaders:{Host:'local.contract.lab',Cookie:session,'X-Source-IP':remote},status:200,reason:'OK',responseHeaders:{'X-Request-ID':`${req}-2`},responseBody:'{"dashboard":"ok"}',artifactId:artifact}];
 const tables:LocalSqlTable[]=[{name:'events',columns:['ts','request_id','session_id','user_id','source_ip','action'],artifactId:artifact,rows:[{ts:'2026-03-20T10:00:00Z',request_id:req,session_id:session,user_id:user,source_ip:'10.2.4.8',action:'session_create'},{ts:'2026-03-20T10:07:00Z',request_id:`${req}-2`,session_id:session,user_id:user,source_ip:remote,action:missionId==='act2-contract-timeline'?'address_export':'dashboard_view'}]}];
 const files:CaseEnvironment['files']={[`${home}/capture.txt`]:{path:`${home}/capture.txt`,artifactId:artifact,content:exchanges.map(x=>`${x.id} ${x.method} ${x.path} ${x.status} ${x.requestHeaders['X-Source-IP']}`).join('\n')},[`${home}/events.jsonl`]:{path:`${home}/events.jsonl`,artifactId:artifact,content:tables[0].rows.map(r=>JSON.stringify(r)).join('\n')}};
 const shell:CaseEnvironment={seed,home,files,directories:[home],facts:{session,remote,req,user},customCommand:({tool,args})=>tool==='http'?runLocalHttpCommand(exchanges,args):tool==='sql'?runLocalSqlCommand(tables,args):null,detectFinding:({raw,stdout,tools})=>{const text=stdout.join('\n');const low=raw.toLowerCase();if(missionId==='act2-contract-http'){if(tools.includes('http')&&low.includes('list'))return'act2-http-method';if(tools.includes('http')&&text.includes('302 Found')&&text.includes('/dashboard'))return'act2-http-chain';if(tools.includes('head')&&text.includes('302')&&text.includes('/dashboard'))return'act2-shell-http-method';if(tools.includes('cat')&&text.includes('302')&&text.includes('/dashboard'))return'act2-http-chain';}
 if(missionId==='act2-contract-session'){if(tools.includes('sql')&&low.includes('tables'))return'act2-sql-session-method';if(tools.includes('sql')&&text.includes(session)&&text.includes(remote)&&text.includes('10.2.4.8'))return'act2-session-reuse';if((tools.includes('grep')||tools.includes('cut'))&&text.includes(session)&&text.includes(remote))return tools.includes('grep')?'act2-session-reuse':'act2-shell-session-method';}
 if(missionId==='act2-contract-timeline'){if(tools.includes('sql')&&low.includes('tables'))return'act2-sql-timeline-method';if(tools.includes('sql')&&text.includes(req)&&text.includes('address_export'))return'act2-data-timeline';if((tools.includes('grep')||tools.includes('sort'))&&text.includes('address_export'))return tools.includes('sort')?'act2-data-timeline':'act2-shell-timeline-method';}return undefined;}};
 return{shell,title:missionId==='act2-contract-http'?'Восстановить HTTP redirect chain':missionId==='act2-contract-session'?'Найти session reuse':'Собрать timeline по request id',objective:missionId==='act2-contract-http'?'Подтверди 302 → 200 и request ids.':missionId==='act2-contract-session'?'Подтверди один session id у двух источников.':'Свяжи session_create и address_export.',client:'Линия',pay:2200+Math.abs(seed)%5*200,evidenceSuggestion:{claimId:`outcome.${missionId}`,evidenceId:artifact,label:'Связать результат контракта',note:'Результат получен выполненной read-only командой на seed dataset.'}};
}
