import type { MissionDefinition } from '../../../core/scenario/types';

export const workspace01Definition: MissionDefinition = {
  schemaVersion: 1,
  id: 'workspace-01',
  chapterId: 'chapter-0.1',
  title: 'Глава 0.1 / Рабочее место',
  level: 'foundation',
  faction: 'independent',
  durationMinutes: 20,
  skills: [
    'computing.filesystem',
    'shell.linux-basics',
    'analysis.evidence-basics',
  ],
  briefing: {
    summary: 'Максим передал локальную очищенную копию материалов CLINIC-01. До анализа журналов нужно уверенно ориентироваться в рабочей среде.',
    objective: 'Найти постановку задачи, затем самостоятельно отыскать второй пакет среди каталогов и зафиксировать найденный файл как evidence.',
    constraints: [
      'Работать только с локальной read-only копией.',
      'Не удалять, не перемещать и не изменять файлы.',
      'Не обращаться к внешней сети.',
      'Не считать имя файла доказательством, пока содержимое не открыто.',
    ],
    hiddenTruth: 'Нужный transfer-файл находится в одном из вложенных каталогов incoming. Старый архив содержит правдоподобный, но неверный код пакета.',
  },
  artifacts: [
    {
      id: 'artifact.workspace.intake',
      title: 'Входящий пакет Максима',
      format: 'local-message',
      origin: 'Максим Белов',
      description: 'Источник, границы и цель локальной учебной копии.',
      containsNoise: false,
    },
    {
      id: 'artifact.workspace.readme',
      title: 'README.txt',
      format: 'text/plain',
      origin: 'Локальный профиль Ильи',
      description: 'Краткие правила рабочего пространства.',
      containsNoise: false,
    },
    {
      id: 'artifact.workspace.brief',
      title: 'CLINIC-01 / brief.txt',
      format: 'text/plain',
      origin: 'Максим Белов / локальная копия',
      description: 'Постановка первой операции и код пакета для самостоятельного поиска.',
      containsNoise: false,
    },
    {
      id: 'artifact.workspace.transfer',
      title: 'Индекс переданного пакета',
      format: 'text/plain',
      origin: 'Локальная входящая папка',
      description: 'Самостоятельно найденный индекс с кодом пакета и происхождением данных.',
      containsNoise: false,
    },
  ],
  outcomes: [
    {
      id: 'outcome.workspace.current-directory',
      skillId: 'computing.filesystem',
      statement: 'Определяет текущий каталог до работы с относительными путями.',
      evidenceType: 'guided',
    },
    {
      id: 'outcome.workspace.navigate-guided',
      skillId: 'shell.linux-basics',
      statement: 'Находит каталог дела и открывает brief безопасными read-only командами.',
      evidenceType: 'guided',
      criticalErrors: ['Изменение исходной копии.', 'Обращение к внешней сети.'],
    },
    {
      id: 'outcome.workspace.transfer',
      skillId: 'computing.filesystem',
      statement: 'Самостоятельно исследует неизвестную ветку каталогов, находит нужный файл и связывает его с задачей.',
      evidenceType: 'independent',
      criticalErrors: ['Выбор старого архива без проверки содержимого.'],
    },
    {
      id: 'outcome.workspace.evidence',
      skillId: 'analysis.evidence-basics',
      statement: 'Фиксирует конкретный открытый артефакт как evidence, а не вводит ответ по памяти.',
      evidenceType: 'independent',
    },
  ],
  hypotheses: [],
  decisions: [],
  assessmentRules: [
    {
      id: 'rule.workspace.started',
      title: 'Глава запущена через mission runtime',
      dimension: 'method',
      weight: 1,
      matcher: { kind: 'event', eventType: 'mission.started' },
    },
    {
      id: 'rule.workspace.intake-opened',
      title: 'Источник и ограничения прочитаны',
      dimension: 'method',
      weight: 2,
      matcher: {
        kind: 'event',
        eventType: 'artifact.opened',
        where: [{ path: 'payload.artifactId', operator: 'eq', value: 'artifact.workspace.intake' }],
      },
    },
    {
      id: 'rule.workspace.pwd',
      title: 'Текущий каталог проверен',
      dimension: 'method',
      weight: 2,
      matcher: {
        kind: 'event',
        eventType: 'command.executed',
        where: [
          { path: 'payload.name', operator: 'eq', value: 'pwd' },
          { path: 'payload.cwd', operator: 'eq', value: '/home/ilya' },
          { path: 'payload.success', operator: 'eq', value: true },
        ],
      },
    },
    {
      id: 'rule.workspace.home-listed',
      title: 'Домашний каталог осмотрен до перехода',
      dimension: 'coverage',
      weight: 2,
      matcher: {
        kind: 'event',
        eventType: 'command.executed',
        where: [
          { path: 'payload.name', operator: 'eq', value: 'ls' },
          { path: 'payload.targetPath', operator: 'eq', value: '/home/ilya' },
          { path: 'payload.success', operator: 'eq', value: true },
        ],
      },
    },
    {
      id: 'rule.workspace.brief-opened',
      title: 'Постановка задачи открыта из файловой системы',
      dimension: 'method',
      weight: 3,
      matcher: {
        kind: 'event',
        eventType: 'artifact.opened',
        where: [{ path: 'payload.artifactId', operator: 'eq', value: 'artifact.workspace.brief' }],
      },
    },
    {
      id: 'rule.workspace.transfer-opened',
      title: 'Новый пакет найден и открыт самостоятельно',
      dimension: 'correctness',
      weight: 4,
      matcher: {
        kind: 'event',
        eventType: 'artifact.opened',
        where: [{ path: 'payload.artifactId', operator: 'eq', value: 'artifact.workspace.transfer' }],
      },
    },
    {
      id: 'rule.workspace.transfer-evidence',
      title: 'Найденный файл связан с observable outcome',
      dimension: 'evidence',
      weight: 4,
      matcher: {
        kind: 'evidence-link',
        claimId: 'outcome.workspace.transfer',
        evidenceIds: ['artifact.workspace.transfer'],
        minLinks: 1,
      },
    },
    {
      id: 'rule.workspace.relative-route',
      title: 'Самостоятельный пакет найден относительным путём',
      dimension: 'efficiency',
      weight: 1,
      matcher: {
        kind: 'event',
        eventType: 'command.executed',
        where: [
          { path: 'payload.targetArtifactId', operator: 'eq', value: 'artifact.workspace.transfer' },
          { path: 'payload.pathMode', operator: 'eq', value: 'relative' },
          { path: 'payload.success', operator: 'eq', value: true },
        ],
      },
    },
    {
      id: 'rule.workspace.absolute-route',
      title: 'Самостоятельный пакет найден абсолютным путём',
      dimension: 'efficiency',
      weight: 1,
      matcher: {
        kind: 'event',
        eventType: 'command.executed',
        where: [
          { path: 'payload.targetArtifactId', operator: 'eq', value: 'artifact.workspace.transfer' },
          { path: 'payload.pathMode', operator: 'eq', value: 'absolute' },
          { path: 'payload.success', operator: 'eq', value: true },
        ],
      },
    },
    {
      id: 'rule.workspace.autonomy',
      title: 'Задание выполнено без раскрытия полного ответа',
      dimension: 'autonomy',
      weight: 1,
      matcher: { kind: 'hint-ceiling', maxTier: 4 },
    },
    {
      id: 'critical.workspace.destructive',
      title: 'Исходная копия не изменялась',
      dimension: 'method',
      weight: 0,
      critical: true,
      matcher: {
        kind: 'event',
        eventType: 'command.executed',
        where: [{ path: 'payload.destructive', operator: 'eq', value: true }],
      },
    },
    {
      id: 'critical.workspace.external-network',
      title: 'Внешняя сеть не использовалась',
      dimension: 'judgment',
      weight: 0,
      critical: true,
      matcher: {
        kind: 'event',
        eventType: 'command.executed',
        where: [{ path: 'payload.externalNetwork', operator: 'eq', value: true }],
      },
    },
  ],
  solutionFamilies: [
    {
      id: 'solution.workspace.relative',
      title: 'Навигация относительными путями',
      description: 'Игрок проверяет текущий каталог и последовательно проходит по дереву файлов.',
      requiredRuleIds: ['rule.workspace.relative-route'],
    },
    {
      id: 'solution.workspace.absolute',
      title: 'Работа абсолютными путями',
      description: 'Игрок использует полный путь к найденному артефакту и получает воспроизводимый результат из любого каталога.',
      requiredRuleIds: ['rule.workspace.absolute-route'],
    },
  ],
  completion: {
    coreRuleIds: [
      'rule.workspace.started',
      'rule.workspace.intake-opened',
      'rule.workspace.pwd',
      'rule.workspace.home-listed',
      'rule.workspace.brief-opened',
      'rule.workspace.transfer-opened',
      'rule.workspace.transfer-evidence',
    ],
    minDimensionScores: {
      correctness: 100,
      evidence: 100,
      method: 100,
      coverage: 100,
    },
  },
  consequences: [
    {
      id: 'consequence.workspace.complete',
      trigger: 'success',
      summary: 'Базовая навигация подтверждена. CLINIC-01 переходит к журналам и процессам.',
      effects: { opensChapter02: true, professionalTrust: 1 },
    },
    {
      id: 'consequence.workspace.destructive',
      trigger: 'critical-error',
      summary: 'Попытка изменения исходной копии требует reset главы и повторного прохождения.',
      effects: { requiresReset: true },
    },
  ],
  replay: {
    seeded: true,
    variables: [
      'transfer-directory',
      'transfer-file-name',
      'case-code',
      'decoy-order',
    ],
  },
  safety: {
    sandboxed: true,
    externalNetwork: false,
    allowedActions: [
      'list-local-directory',
      'change-local-directory',
      'read-local-file',
      'inspect-local-metadata',
      'link-evidence',
    ],
    resettable: true,
  },
};
