import type { MissionDefinition } from '../../../core/scenario/types';
export const marshrutInvestigation01Definition:MissionDefinition={
 schemaVersion:1,id:'marshrut-investigation-01',chapterId:'chapter-2.1',title:'МАРШРУТ-01 / Ночная сессия',level:'junior',faction:'north',durationMinutes:90,
 skills:['web.http-observation','identity.session-analysis','data.sql-analysis','analysis.timeline','communication.boundaries','incident.session-response'],
 briefing:{summary:'Игорь передал локальную копию журналов службы доставки. Один session id использован из двух сетей, затем создан экспорт маршрута.',objective:'Восстановить HTTP и session timeline, отделить факт reuse от недоказанного password compromise и решить, кому передать результат.',constraints:['Только локальный синтетический стенд.','Cookie и полные маршруты нельзя передавать заказчику.','HTTP 200 подтверждает действие сервиса, но не объясняет происхождение session.','Исходные данные read-only.'],hiddenTruth:'Сессия создана из штатной сети и позже использована с внешнего адреса для route_export. Утечки пароля или нового login с внешнего адреса нет.'},
 artifacts:[
  {id:'artifact.route.brief',title:'brief.txt',format:'text/plain',origin:'Игорь / локальная передача',description:'Условия и границы передачи данных.',containsNoise:false},
  {id:'artifact.route.http',title:'captured-http',format:'HTTP/1.1 exchanges',origin:'local reverse proxy',description:'Запросы и ответы локального сервиса.',containsNoise:true},
  {id:'artifact.route.access',title:'access.jsonl',format:'jsonl/access-log',origin:'application gateway',description:'Request id, session, source, path и status.',containsNoise:true},
  {id:'artifact.route.sessions',title:'sessions table',format:'sqlite/table',origin:'session database copy',description:'Создание session и исходный адрес.',containsNoise:false},
  {id:'artifact.route.audit',title:'request_audit table',format:'sqlite/table',origin:'audit database copy',description:'Действия по request id и session.',containsNoise:true},
 ],
 outcomes:[
  {id:'outcome.route.http',skillId:'web.http-observation',statement:'Читает method, path, headers, cookie, status и request id.',evidenceType:'guided'},
  {id:'outcome.route.session',skillId:'identity.session-analysis',statement:'Подтверждает использование одной session из двух сетей.',evidenceType:'guided'},
  {id:'outcome.route.sql',skillId:'data.sql-analysis',statement:'Использует read-only SELECT для проверки session и audit.',evidenceType:'independent'},
  {id:'outcome.route.timeline',skillId:'analysis.timeline',statement:'Строит воспроизводимую временную линию по request id.',evidenceType:'independent'},
  {id:'outcome.route.boundaries',skillId:'communication.boundaries',statement:'Не передаёт cookie и лишние персональные данные.',evidenceType:'independent'},
  {id:'outcome.route.response',skillId:'incident.session-response',statement:'Выбирает отзыв session и сохранение evidence.',evidenceType:'guided'},
 ],
 hypotheses:[
  {id:'hypothesis.route.reuse',title:'Одна session использована из двух сетей',description:'Session id встречается у штатного и внешнего источника.',allowedStatuses:['open','supported','rejected','unknown']},
  {id:'hypothesis.route.password',title:'Пароль пользователя скомпрометирован',description:'Внешний источник выполнил новый login.',allowedStatuses:['open','supported','rejected','unknown']},
  {id:'hypothesis.route.export',title:'Маршрут экспортирован',description:'Audit и HTTP подтверждают export.',allowedStatuses:['open','supported','rejected','unknown']},
  {id:'hypothesis.route.normal-device',title:'Все запросы пришли с обычного устройства',description:'Источник и session usage не менялись.',allowedStatuses:['open','supported','rejected','unknown']},
 ],
 decisions:[
  {id:'decision.route.revoke-notify',title:'Отозвать session и уведомить владельца',description:'Сохранить evidence, отозвать session, уведомить владельца сервиса и передать Игорю только технический минимум.',risk:'low'},
  {id:'decision.route.suspend-coordinate',title:'Приостановить учётку и согласовать восстановление',description:'Сохранить evidence, временно приостановить учётку и провести восстановление с владельцем.',risk:'medium'},
  {id:'decision.route.send-secrets',title:'Отправить cookie и полный экспорт Игорю',description:'Передать действующую session и персональные маршруты без отзыва.',risk:'high'},
 ],
 assessmentRules:[
  {id:'rule.route.started',title:'Миссия запущена',dimension:'method',weight:1,matcher:{kind:'event',eventType:'mission.started'}},
  {id:'rule.route.http',title:'HTTP session создана',dimension:'correctness',weight:3,matcher:{kind:'event',eventType:'command.executed',where:[{path:'payload.finding',operator:'eq',value:'route-http-session'}]}},
  {id:'rule.route.reuse',title:'Session reuse подтверждён',dimension:'correctness',weight:4,matcher:{kind:'event',eventType:'command.executed',where:[{path:'payload.finding',operator:'eq',value:'route-session-reuse'}]}},
  {id:'rule.route.export',title:'Export подтверждён',dimension:'correctness',weight:3,matcher:{kind:'event',eventType:'command.executed',where:[{path:'payload.finding',operator:'eq',value:'route-export'}]}},
  {id:'rule.route.timeline',title:'Timeline построен',dimension:'coverage',weight:3,matcher:{kind:'event',eventType:'command.executed',where:[{path:'payload.finding',operator:'eq',value:'route-timeline'}]}},
  {id:'rule.route.h-reuse',title:'Reuse поддержан',dimension:'judgment',weight:2,matcher:{kind:'hypothesis',hypothesisId:'hypothesis.route.reuse',statuses:['supported']}},
  {id:'rule.route.h-password',title:'Password compromise не выдуман',dimension:'judgment',weight:3,matcher:{kind:'hypothesis',hypothesisId:'hypothesis.route.password',statuses:['rejected','unknown']}},
  {id:'rule.route.h-export',title:'Export поддержан',dimension:'judgment',weight:2,matcher:{kind:'hypothesis',hypothesisId:'hypothesis.route.export',statuses:['supported']}},
  {id:'rule.route.h-device',title:'Нормальное устройство отвергнуто',dimension:'judgment',weight:2,matcher:{kind:'hypothesis',hypothesisId:'hypothesis.route.normal-device',statuses:['rejected']}},
  {id:'rule.route.e-http',title:'HTTP связан',dimension:'evidence',weight:2,matcher:{kind:'evidence-link',claimId:'outcome.route.http',evidenceIds:['artifact.route.http']}},
  {id:'rule.route.e-reuse',title:'Sessions связаны',dimension:'evidence',weight:2,matcher:{kind:'evidence-link',claimId:'hypothesis.route.reuse',evidenceIds:['artifact.route.audit']}},
  {id:'rule.route.e-export',title:'Audit связан с export',dimension:'evidence',weight:2,matcher:{kind:'evidence-link',claimId:'hypothesis.route.export',evidenceIds:['artifact.route.audit']}},
  {id:'rule.route.e-timeline',title:'Access связан с timeline',dimension:'evidence',weight:2,matcher:{kind:'evidence-link',claimId:'outcome.route.timeline',evidenceIds:['artifact.route.access']}},
  {id:'rule.route.report',title:'Отчёт завершён',dimension:'communication',weight:4,matcher:{kind:'report',requiredSections:['facts','evidence','limitations','decision','nextSteps']}},
  {id:'rule.route.hints',title:'Подсказки ограничены',dimension:'autonomy',weight:1,matcher:{kind:'hint-ceiling',maxTier:4}},
  {id:'rule.route.revoke',title:'Session отозвана',dimension:'judgment',weight:1,matcher:{kind:'decision',decisionIds:['decision.route.revoke-notify']}},
  {id:'rule.route.suspend',title:'Учётка приостановлена',dimension:'judgment',weight:1,matcher:{kind:'decision',decisionIds:['decision.route.suspend-coordinate']}},
  {id:'critical.route.secrets',title:'Секреты не переданы',dimension:'judgment',weight:0,critical:true,matcher:{kind:'decision',decisionIds:['decision.route.send-secrets']}},
  {id:'critical.route.destructive',title:'Evidence не изменён',dimension:'method',weight:0,critical:true,matcher:{kind:'event',eventType:'command.executed',where:[{path:'payload.destructive',operator:'eq',value:true}]}},
  {id:'critical.route.network',title:'Внешняя сеть не использована',dimension:'judgment',weight:0,critical:true,matcher:{kind:'event',eventType:'command.executed',where:[{path:'payload.externalNetwork',operator:'eq',value:true}]}},
 ],
 solutionFamilies:[{id:'solution.route.revoke',title:'Отзыв session',description:'Точечный response и уведомление владельца.',requiredRuleIds:['rule.route.revoke']},{id:'solution.route.suspend',title:'Приостановка учётки',description:'Более жёсткое ограничение с восстановлением.',requiredRuleIds:['rule.route.suspend']}],
 completion:{coreRuleIds:['rule.route.started','rule.route.http','rule.route.reuse','rule.route.export','rule.route.timeline','rule.route.h-reuse','rule.route.h-password','rule.route.h-export','rule.route.h-device','rule.route.e-http','rule.route.e-reuse','rule.route.e-export','rule.route.e-timeline','rule.route.report'],minDimensionScores:{correctness:100,evidence:100,coverage:100,communication:100,judgment:80}},
 consequences:[{id:'consequence.route.complete',trigger:'success',summary:'Игорь получает технический минимум. Открываются самостоятельные контракты.',effects:{northTrust:1,opensAct2Contracts:true}},{id:'consequence.route.revoke',trigger:'decision',decisionId:'decision.route.revoke-notify',summary:'Владелец отозвал session без остановки сервиса.',effects:{containment:2,downtime:0}},{id:'consequence.route.secrets',trigger:'critical-error',summary:'Передача cookie блокирует завершение.',effects:{requiresReset:true,digitalRisk:4}}],
 replay:{seeded:true,variables:['session','user','normal-ip','remote-ip','route-id']},safety:{sandboxed:true,externalNetwork:false,allowedActions:['inspect-local-http','query-local-sql','read-local-logs','link-evidence','submit-local-report'],resettable:true}
};
