import { useState } from 'react';
import { ArrowRight, CheckCircle2, Crosshair, FileSearch, LockKeyhole, Radar, SearchCode, ShieldCheck, TerminalSquare, XCircle } from 'lucide-react';
import { useProgress } from '../system/ProgressContext';
import { huntArchitecture, huntCaseOverview, huntFoundationQuestions, huntGuidedObjectives, huntHypothesisQuestions, huntIndependentCommands, huntIndependentQuestions, huntReportSections, huntTuningQuestions, kqlSolution, sigmaSolution, sigmaStarter } from '../missions/threatHunt01';

type SelectKey = 'huntCaseFoundationAnswers'|'huntCaseHypothesisAnswers'|'huntCaseTuningSelections'|'huntCaseIndependentAnswers'|'huntCaseReportSelections';
type HistoryEntry = { command:string; output:string; ok:boolean };
const stages=['Вводная','Основа','Гипотеза','Телеметрия','Sigma / KQL','Tuning','Самостоятельная охота / Отчёт','Готово'];
const norm=(v:string)=>v.trim().toLowerCase().replace(/\s+/g,' ');
const allCorrect=(sections:readonly {id:string;options:readonly {id:string;correct?:boolean}[]}[], selected:Record<string,string>)=>sections.every(s=>s.options.find(o=>o.id===selected[s.id])?.correct);

export function ThreatHuntCaseApp(){
 const {progress,setFlag,completeHuntCase}=useProgress();
 const stage=Math.max(0,Math.min(7,progress.huntCaseStage));
 const [checked,setChecked]=useState<Record<string,boolean>>({});
 const [command,setCommand]=useState(''); const [history,setHistory]=useState<HistoryEntry[]>([]);
 const [indCommand,setIndCommand]=useState(''); const [indHistory,setIndHistory]=useState<HistoryEntry[]>([]);
 const next=huntGuidedObjectives.find(o=>!progress.huntCaseObjectives.includes(o.id));
 const guidedDone=huntGuidedObjectives.every(o=>progress.huntCaseObjectives.includes(o.id));
 const indDone=huntIndependentCommands.every(o=>progress.huntCaseIndependentObjectives.includes(o.id));
 const setStage=(v:number)=>setFlag('huntCaseStage',Math.max(progress.huntCaseStage,Math.min(7,v)));
 const choose=(key:SelectKey,section:string,id:string)=>{setFlag(key,{...progress[key],[section]:id});setChecked(c=>({...c,[key]:false}));};
 const options=(sections:readonly {id:string;label:string;options:readonly {id:string;text:string;correct?:boolean}[]}[], selected:Record<string,string>, key:SelectKey)=><div className="windows-question-stack hunt-question-stack">{sections.map(s=><article className="windows-question-card" key={s.id}><h3>{s.label}</h3><div>{s.options.map(o=>{const active=selected[s.id]===o.id;const status=checked[key]&&active?(o.correct?'correct':'wrong'):'';return <button key={o.id} className={`${active?'selected':''} ${status}`} onClick={()=>choose(key,s.id,o.id)}><span>{active?'●':'○'}</span><p>{o.text}</p>{checked[key]&&active&&(o.correct?<CheckCircle2 size={17}/>:<XCircle size={17}/>)}</button>})}</div></article>)}</div>;
 const verify=(key:SelectKey,sections:readonly {id:string;options:readonly {id:string;correct?:boolean}[]}[],to:number)=>{setChecked(c=>({...c,[key]:true}));if(allCorrect(sections,progress[key]))setStage(to)};
 const match=(expected:string,raw:string)=>{const a=norm(expected),b=norm(raw);if(a===b)return true;return a.split(' ').filter(x=>x.includes('=')||x.startsWith('t10')||x.includes('baseline')||x.includes('telemetry')).every(x=>b.includes(x.replace(/"/g,'')))&&b.includes('hunt')};
 const run=()=>{if(!next||!command.trim())return;const ok=match(next.command,command);setHistory(h=>[...h,{command,output:ok?next.output:`Сейчас нужно: ${next.title}.`,ok}]);setCommand('');if(ok)setFlag('huntCaseObjectives',[...progress.huntCaseObjectives,next.id])};
 const runIndependent=()=>{if(!indCommand.trim())return;const found=huntIndependentCommands.find(o=>match(o.command,indCommand));setIndHistory(h=>[...h,{command:indCommand,output:found?found.output:'Источник доступен, но запрос не проверяет нужную гипотезу.',ok:Boolean(found)}]);setIndCommand('');if(found&&!progress.huntCaseIndependentObjectives.includes(found.id))setFlag('huntCaseIndependentObjectives',[...progress.huntCaseIndependentObjectives,found.id])};
 const sigmaOk=/service_user[\s\S]*svc_/i.test(progress.huntCaseSigma)&&/interactive_chain[\s\S]*powershell/i.test(progress.huntCaseSigma)&&/rundll32/i.test(progress.huntCaseSigma)&&/not filter_admin/i.test(progress.huntCaseSigma);
 const kqlOk=/DeviceProcessEvents/.test(progress.huntCaseKql)&&/AccountName startswith "svc_"/.test(progress.huntCaseKql)&&/InitiatingProcessFileName/.test(progress.huntCaseKql)&&/summarize/.test(progress.huntCaseKql)&&/Hosts <= 2/.test(progress.huntCaseKql);
 const finish=()=>{setChecked(c=>({...c,huntCaseIndependentAnswers:true,huntCaseReportSelections:true}));if(indDone&&allCorrect(huntIndependentQuestions,progress.huntCaseIndependentAnswers)&&allCorrect(huntReportSections,progress.huntCaseReportSelections))setStage(7)};
 return <div className="route-case-app windows-case-app incident-case-app hunt-case-app"><aside className="route-case-sidebar windows-case-sidebar hunt-case-sidebar"><header><p className="eyebrow">NIGHTGLASS-10</p><h2>Threat Hunting</h2><span>NO READY ALERT</span></header><nav>{stages.map((name,i)=><button key={name} disabled className={`${i===stage?'active':''} ${i<stage?'done':''}`}><span>{i<stage?'✓':String(i+1).padStart(2,'0')}</span><strong>{name}</strong></button>)}</nav><footer><LockKeyhole size={15}/><div><strong>HUNT LAKE</strong><span>synthetic telemetry</span></div></footer></aside>
 <main className="route-case-main windows-case-main hunt-case-main app-scroll">
 {stage===0&&<section className="route-brief-stage windows-brief-stage"><header><Crosshair size={29}/><div><p className="eyebrow">CASE / NIGHTGLASS-10</p><h1>Алерта нет. Следы есть.</h1></div></header><div className="route-brief-grid windows-brief-grid">{huntCaseOverview.map(i=><div key={i.label}><span>{i.label}</span><strong>{i.value}</strong></div>)}</div><div className="windows-theory warning"><strong>Greylock / access broker</strong><p>После прошлой атаки правила молчат. В логах за месяц есть странные входы сервисных учёток. Проверь гипотезу, а не ищи заранее известный IP.</p></div><div className="incident-architecture-grid">{huntArchitecture.map(i=><article key={i.id}><span>{i.role}</span><Radar size={20}/><strong>{i.title}</strong><p>{i.subtitle}</p><code>{i.address}</code></article>)}</div><button className="primary-action full" onClick={()=>setStage(1)}>Начать охоту<ArrowRight size={17}/></button></section>}
 {stage===1&&<section className="route-choice-stage"><header><FileSearch size={23}/><div><p className="eyebrow">HUNT FUNDAMENTALS</p><h2>Гипотеза, TTP и требования к данным</h2></div></header>{options(huntFoundationQuestions,progress.huntCaseFoundationAnswers,'huntCaseFoundationAnswers')}<button className="primary-action full" onClick={()=>verify('huntCaseFoundationAnswers',huntFoundationQuestions,2)}>Проверить основу<ArrowRight size={17}/></button></section>}
 {stage===2&&<section className="route-choice-stage"><header><Crosshair size={23}/><div><p className="eyebrow">HYPOTHESIS</p><h2>Сформулируй проверяемое поведение</h2></div></header><div className="windows-theory"><strong>Структура</strong><p>Техника → актив → ожидаемое наблюдение → источники → критерий завершения.</p></div>{options(huntHypothesisQuestions,progress.huntCaseHypothesisAnswers,'huntCaseHypothesisAnswers')}<button className="primary-action full" onClick={()=>verify('huntCaseHypothesisAnswers',huntHypothesisQuestions,3)}>Перейти к телеметрии<ArrowRight size={17}/></button></section>}
 {stage===3&&<section className="windows-terminal-stage"><header><TerminalSquare size={23}/><div><p className="eyebrow">DATA REQUIREMENTS</p><h2>Baseline, rare behavior и telemetry gaps</h2></div></header><div className="windows-theory"><strong>{next?.title??'Сбор завершён'}</strong><p>{next?'Сначала пойми, какой вопрос отвечает запрос. Потом запускай его.':'Теперь поведение связано между identity, endpoint и network.'}</p>{next&&<code>{next.command}</code>}</div><div className="windows-terminal-box"><div className="windows-terminal-history">{history.map((e,i)=><div key={i}><code>$ {e.command}</code><pre className={e.ok?'':'error'}>{e.output}</pre></div>)}</div>{next&&<div className="windows-terminal-input"><span>$</span><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()} placeholder="hunt query ..."/><button onClick={()=>{setCommand(next.command);setFlag('huntCaseHintUses',progress.huntCaseHintUses+1)}}>Вставить</button><button className="primary-action" onClick={run}>Выполнить</button></div>}</div>{guidedDone&&<button className="primary-action full" onClick={()=>setStage(4)}>Написать аналитику<ArrowRight size={17}/></button>}</section>}
 {stage===4&&<section className="hunt-code-stage"><header><SearchCode size={23}/><div><p className="eyebrow">DETECTION ENGINEERING</p><h2>Sigma и KQL</h2></div></header><div className="web-code-workspace"><div className="web-code-reference"><span>Слишком широкое Sigma-правило</span><pre>{sigmaStarter}</pre></div><div className="web-code-editor"><span>Твой Sigma</span><textarea spellCheck={false} value={progress.huntCaseSigma} onChange={e=>setFlag('huntCaseSigma',e.target.value)}/><button onClick={()=>{setFlag('huntCaseSigma',sigmaSolution);setFlag('huntCaseHintUses',progress.huntCaseHintUses+1)}}>Вставить рабочий вариант</button></div></div><div className="web-code-workspace"><div className="web-code-reference"><span>Задача KQL</span><pre>Найди редкие цепочки svc_* → PowerShell → Rundll32 за 30 дней. Сгруппируй по учётке и командной строке.</pre></div><div className="web-code-editor"><span>Твой KQL</span><textarea spellCheck={false} value={progress.huntCaseKql} onChange={e=>setFlag('huntCaseKql',e.target.value)}/><button onClick={()=>{setFlag('huntCaseKql',kqlSolution);setFlag('huntCaseHintUses',progress.huntCaseHintUses+1)}}>Вставить рабочий вариант</button></div></div><button className="primary-action full" onClick={()=>sigmaOk&&kqlOk&&setStage(5)}>Проверить аналитику<ArrowRight size={17}/></button>{(!sigmaOk||!kqlOk)&&<small>Проверка требует поведения, контекста и агрегации, а не одного имени процесса.</small>}</section>}
 {stage===5&&<section className="route-choice-stage"><header><Radar size={23}/><div><p className="eyebrow">TUNING & VALIDATION</p><h2>False positives, тесты и пробелы</h2></div></header>{options(huntTuningQuestions,progress.huntCaseTuningSelections,'huntCaseTuningSelections')}<button className="primary-action full" onClick={()=>verify('huntCaseTuningSelections',huntTuningQuestions,6)}>Начать самостоятельную охоту<ArrowRight size={17}/></button></section>}
 {stage===6&&<section className="windows-terminal-stage"><header><Crosshair size={23}/><div><p className="eyebrow">INDEPENDENT HUNT</p><h2>Второй набор без готового порядка</h2></div></header><div className="windows-theory"><strong>Гипотеза</strong><p>Сервисная учётка резервного копирования могла использоваться на нетипичном Linux build-host для передачи данных. Сам выбери источники и собери цепочку.</p></div><div className="windows-terminal-box"><div className="windows-terminal-history">{indHistory.map((e,i)=><div key={i}><code>$ {e.command}</code><pre className={e.ok?'':'error'}>{e.output}</pre></div>)}</div><div className="windows-terminal-input"><span>$</span><input value={indCommand} onChange={e=>setIndCommand(e.target.value)} onKeyDown={e=>e.key==='Enter'&&runIndependent()} placeholder="hunt query ..."/><button onClick={()=>setFlag('huntCaseHintUses',progress.huntCaseHintUses+1)}>Подсказка в отчёте</button><button className="primary-action" onClick={runIndependent}>Выполнить</button></div></div>{options(huntIndependentQuestions,progress.huntCaseIndependentAnswers,'huntCaseIndependentAnswers')}{options(huntReportSections,progress.huntCaseReportSelections,'huntCaseReportSelections')}<button className="primary-action full" onClick={finish}>Закрыть hunt<ArrowRight size={17}/></button></section>}
 {stage===7&&<section className="route-wrap windows-wrap"><ShieldCheck size={52}/><p className="eyebrow">NIGHTGLASS-10 / ЗАВЕРШЕНО</p><h1>Поведение найдено без готового алерта</h1><p>Ты построил гипотезу, проверил источники, нашёл telemetry gaps, написал Sigma/KQL, провёл tuning и повторил охоту на втором наборе.</p><small>Подсказок: {progress.huntCaseHintUses}</small><button className="primary-action" onClick={completeHuntCase}>Закрыть дело</button></section>}
 </main></div>
}
