import type { MissionDefinition } from '../../../core/scenario/types';

export const sferaShiftCheck01Definition: MissionDefinition = {
  schemaVersion: 1,
  id: 'sfera-shift-check-01',
  chapterId: 'chapter-1.2',
  title: 'SHIFT-01 / Первая смена',
  level: 'junior',
  faction: 'sfera',
  durationMinutes: 90,
  skills: [
    'soc.telemetry',
    'soc.triage',
    'analysis.scope',
    'endpoint.process-chain',
    'network.dns-analysis',
    'communication.handoff',
    'incident.initial-response',
  ],
  briefing: {
    summary: 'Первая самостоятельная смена: четыре сигнала, один из них легитимный. Тип цепочки и правильный порядок не раскрыты.',
    objective: 'Самостоятельно расставить приоритеты, связать telemetry, определить scope, выбрать containment и передать второй линии полный handoff.',
    constraints: [
      'Подсказки отключены.',
      'Узел бухгалтерии критичен, но доступно резервное рабочее место.',
      'Нельзя считать все сигналы одной атакой без correlation.',
      'Нельзя закрывать queue только по severity.',
    ],
    hiddenTruth: 'Письмо, endpoint и DNS относятся к FIN-WS-09. AUTH-события не подтверждают внешнюю успешную сессию. Backup alert на SRV-BACKUP-02 легитимен и не связан с цепочкой.',
  },
  artifacts: [
    { id: 'artifact.shift.brief', title: 'shift-brief.txt', format: 'text/plain', origin: 'Кирилл Зорин', description: 'Ограничения первой смены.', containsNoise: false },
    { id: 'artifact.shift.alerts', title: 'alerts.jsonl', format: 'jsonl/siem-alerts', origin: 'WATCHTOWER SIEM', description: 'Очередь из четырёх сигналов.', containsNoise: true },
    { id: 'artifact.shift.mail', title: 'payment_notice.eml', format: 'message/rfc822', origin: 'Mail Gateway', description: 'Письмо бухгалтерии.', containsNoise: true },
    { id: 'artifact.shift.processes', title: 'processes.csv', format: 'csv/process-tree', origin: 'EDR Snapshot', description: 'Процессы нескольких хостов.', containsNoise: true },
    { id: 'artifact.shift.dns', title: 'dns.log', format: 'dns-telemetry', origin: 'Resolver', description: 'DNS-запросы офиса.', containsNoise: true },
    { id: 'artifact.shift.auth', title: 'identity.log', format: 'identity-telemetry', origin: 'Identity Provider', description: 'Сессии и MFA.', containsNoise: true },
    { id: 'artifact.shift.assets', title: 'assets.csv', format: 'csv/asset-inventory', origin: 'CMDB', description: 'Хосты, владельцы и критичность.', containsNoise: false },
    { id: 'artifact.shift.backup', title: 'backup-job.log', format: 'application-log', origin: 'Backup Platform', description: 'Легитимная ночная задача.', containsNoise: false },
  ],
  outcomes: [
    { id: 'outcome.shift.priority', skillId: 'soc.triage', statement: 'Приоритизирует связанные mail, endpoint и DNS сигналы выше легитимного backup alert.', evidenceType: 'transfer' },
    { id: 'outcome.shift.chain', skillId: 'endpoint.process-chain', statement: 'Связывает письмо, process chain и DNS по пользователю, хосту, PID и времени.', evidenceType: 'transfer' },
    { id: 'outcome.shift.scope', skillId: 'analysis.scope', statement: 'Ограничивает подтверждённый scope одним хостом и не выдумывает account compromise.', evidenceType: 'transfer' },
    { id: 'outcome.shift.response', skillId: 'incident.initial-response', statement: 'Выбирает containment с резервом и сохранением evidence.', evidenceType: 'transfer' },
    { id: 'outcome.shift.handoff', skillId: 'communication.handoff', statement: 'Передаёт второй линии воспроизводимый отчёт.', evidenceType: 'transfer' },
  ],
  hypotheses: [
    { id: 'hypothesis.shift.chain', title: 'Mail, endpoint и DNS образуют одну цепочку', description: 'События относятся к одному пользователю и FIN-WS-09.', allowedStatuses: ['open', 'supported', 'rejected', 'unknown'] },
    { id: 'hypothesis.shift.account', title: 'Внешняя успешная сессия бухгалтера', description: 'Identity telemetry подтверждает новую внешнюю сессию.', allowedStatuses: ['open', 'supported', 'rejected', 'unknown'] },
    { id: 'hypothesis.shift.second-host', title: 'Второй рабочий хост затронут', description: 'Есть evidence исполнения или beaconing на другом workstation.', allowedStatuses: ['open', 'supported', 'rejected', 'unknown'] },
    { id: 'hypothesis.shift.backup', title: 'Backup alert связан с инцидентом', description: 'SRV-BACKUP-02 участвует в той же цепочке.', allowedStatuses: ['open', 'supported', 'rejected', 'unknown'] },
  ],
  decisions: [
    { id: 'decision.shift.isolate-reserve', title: 'Изолировать FIN-WS-09 и выдать резерв', description: 'Сохранить volatile telemetry, изолировать endpoint, блокировать домен, проверить сессии и перевести сотрудника на резерв.', risk: 'low' },
    { id: 'decision.shift.restrict-monitor', title: 'Ограничить связь и усилить мониторинг', description: 'Заблокировать домен и процессную связь, сохранить evidence, передать узел второй линии и контролировать сессии.', risk: 'medium' },
    { id: 'decision.shift.close-all', title: 'Закрыть очередь как ложные срабатывания', description: 'Не сохранять evidence и не выполнять containment.', risk: 'high' },
  ],
  assessmentRules: [
    { id: 'rule.shift.started', title: 'Смена начата', dimension: 'method', weight: 1, matcher: { kind: 'event', eventType: 'mission.started' } },
    { id: 'rule.shift.queue-mail', title: 'Mail alert исследован', dimension: 'method', weight: 1, matcher: { kind: 'event', eventType: 'query.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'shift-queue-mail' }] } },
    { id: 'rule.shift.queue-endpoint', title: 'Endpoint alert исследован', dimension: 'method', weight: 1, matcher: { kind: 'event', eventType: 'query.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'shift-queue-endpoint' }] } },
    { id: 'rule.shift.queue-dns', title: 'DNS alert исследован', dimension: 'method', weight: 1, matcher: { kind: 'event', eventType: 'query.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'shift-queue-dns' }] } },
    { id: 'rule.shift.queue-backup', title: 'Backup alert проверен', dimension: 'coverage', weight: 1, matcher: { kind: 'event', eventType: 'query.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'shift-queue-backup' }] } },
    { id: 'rule.shift.mail', title: 'Письмо подтверждено', dimension: 'correctness', weight: 2, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'shift-mail-finding' }] } },
    { id: 'rule.shift.process', title: 'Process chain подтверждена', dimension: 'correctness', weight: 3, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'shift-process-chain' }] } },
    { id: 'rule.shift.dns', title: 'DNS связан с хостом', dimension: 'correctness', weight: 3, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'shift-dns-correlation' }] } },
    { id: 'rule.shift.auth', title: 'Identity scope проверен', dimension: 'coverage', weight: 2, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'shift-auth-scope' }] } },
    { id: 'rule.shift.backup', title: 'Backup job проверен', dimension: 'coverage', weight: 2, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'shift-backup-legitimate' }] } },
    { id: 'rule.shift.chain-hypothesis', title: 'Цепочка поддержана', dimension: 'judgment', weight: 3, matcher: { kind: 'hypothesis', hypothesisId: 'hypothesis.shift.chain', statuses: ['supported'] } },
    { id: 'rule.shift.account-hypothesis', title: 'Account compromise не выдуман', dimension: 'judgment', weight: 3, matcher: { kind: 'hypothesis', hypothesisId: 'hypothesis.shift.account', statuses: ['rejected', 'unknown'] } },
    { id: 'rule.shift.second-host-hypothesis', title: 'Второй host не выдуман', dimension: 'judgment', weight: 2, matcher: { kind: 'hypothesis', hypothesisId: 'hypothesis.shift.second-host', statuses: ['rejected', 'unknown'] } },
    { id: 'rule.shift.backup-hypothesis', title: 'Backup отделён от инцидента', dimension: 'judgment', weight: 2, matcher: { kind: 'hypothesis', hypothesisId: 'hypothesis.shift.backup', statuses: ['rejected'] } },
    { id: 'rule.shift.chain-evidence', title: 'Process evidence связано с цепочкой', dimension: 'evidence', weight: 2, matcher: { kind: 'evidence-link', claimId: 'hypothesis.shift.chain', evidenceIds: ['artifact.shift.processes'] } },
    { id: 'rule.shift.dns-evidence', title: 'DNS evidence связано с цепочкой', dimension: 'evidence', weight: 2, matcher: { kind: 'evidence-link', claimId: 'outcome.shift.chain', evidenceIds: ['artifact.shift.dns'] } },
    { id: 'rule.shift.scope-evidence', title: 'Identity evidence связано со scope', dimension: 'evidence', weight: 2, matcher: { kind: 'evidence-link', claimId: 'outcome.shift.scope', evidenceIds: ['artifact.shift.auth'] } },
    { id: 'rule.shift.backup-evidence', title: 'Backup evidence связано с исключением', dimension: 'evidence', weight: 2, matcher: { kind: 'evidence-link', claimId: 'hypothesis.shift.backup', evidenceIds: ['artifact.shift.backup'] } },
    { id: 'rule.shift.report', title: 'Handoff завершён', dimension: 'communication', weight: 4, matcher: { kind: 'report', requiredSections: ['facts', 'evidence', 'limitations', 'decision', 'nextSteps'] } },
    { id: 'rule.shift.isolate', title: 'Изоляция с резервом', dimension: 'judgment', weight: 1, matcher: { kind: 'decision', decisionIds: ['decision.shift.isolate-reserve'] } },
    { id: 'rule.shift.restrict', title: 'Ограничение и мониторинг', dimension: 'judgment', weight: 1, matcher: { kind: 'decision', decisionIds: ['decision.shift.restrict-monitor'] } },
    { id: 'critical.shift.close', title: 'Инцидент не закрыт без проверки', dimension: 'judgment', weight: 0, critical: true, matcher: { kind: 'decision', decisionIds: ['decision.shift.close-all'] } },
    { id: 'critical.shift.hint', title: 'Подсказки отсутствуют', dimension: 'autonomy', weight: 0, critical: true, matcher: { kind: 'event', eventType: 'hint.used' } },
    { id: 'critical.shift.destructive', title: 'Evidence не уничтожен', dimension: 'method', weight: 0, critical: true, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.destructive', operator: 'eq', value: true }] } },
    { id: 'critical.shift.network', title: 'Нет внешней сети', dimension: 'judgment', weight: 0, critical: true, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.externalNetwork', operator: 'eq', value: true }] } },
  ],
  solutionFamilies: [
    { id: 'solution.shift.isolate', title: 'Изоляция с резервом', description: 'Минимизировать риск, сохранив работу бухгалтерии.', requiredRuleIds: ['rule.shift.isolate'] },
    { id: 'solution.shift.restrict', title: 'Точечное ограничение', description: 'Ограничить коммуникации и передать полный пакет второй линии.', requiredRuleIds: ['rule.shift.restrict'] },
  ],
  completion: {
    coreRuleIds: [
      'rule.shift.started', 'rule.shift.queue-mail', 'rule.shift.queue-endpoint', 'rule.shift.queue-dns', 'rule.shift.queue-backup',
      'rule.shift.mail', 'rule.shift.process', 'rule.shift.dns', 'rule.shift.auth', 'rule.shift.backup',
      'rule.shift.chain-hypothesis', 'rule.shift.account-hypothesis', 'rule.shift.second-host-hypothesis', 'rule.shift.backup-hypothesis',
      'rule.shift.chain-evidence', 'rule.shift.dns-evidence', 'rule.shift.scope-evidence', 'rule.shift.backup-evidence', 'rule.shift.report',
    ],
    minDimensionScores: { correctness: 100, evidence: 100, method: 100, coverage: 100, communication: 100, judgment: 80 },
  },
  consequences: [
    { id: 'consequence.shift.complete', trigger: 'success', summary: 'Первая смена закрыта. Открываются основная игра и серые контакты.', effects: { firstShiftComplete: true, sferaTrust: 3, opensMainGame: true } },
    { id: 'consequence.shift.isolate', trigger: 'decision', decisionId: 'decision.shift.isolate-reserve', summary: 'Бухгалтерия работает с резервного места.', effects: { downtime: 1, containment: 2 } },
    { id: 'consequence.shift.close', trigger: 'critical-error', summary: 'Непроверенная очередь возвращена на разбор.', effects: { requiresReset: true } },
  ],
  replay: { seeded: true, variables: ['host', 'user', 'domain', 'pid', 'remote', 'alert-order', 'benign-alert'] },
  safety: { sandboxed: true, externalNetwork: false, allowedActions: ['open-local-alert', 'read-local-artifact', 'filter-local-telemetry', 'link-evidence', 'submit-local-report'], resettable: true },
};
