import { useMemo, useState } from 'react';
import { ArrowRight, CircleHelp, RotateCcw, ShieldCheck } from 'lucide-react';
import { CaseShellPanel } from './CaseShellPanel';
import { CaseReasoningPanel } from './CaseReasoningPanel';
import { createMarshrutEnvironment } from '../content/missions/marshrutInvestigation01/environment';
import { getMissionDefinition } from '../content/missions/registry';
import { useMissionRuntime } from '../system/MissionRuntimeContext';

const evidence=[
 {claimId:'outcome.route.http',evidenceId:'artifact.route.http',label:'HTTP → captured exchange',note:'Method, path, headers, cookie и response получены из local replay.'},
 {claimId:'hypothesis.route.reuse',evidenceId:'artifact.route.audit',label:'Reuse → request_audit',note:'Один session id связан с двумя source IP.'},
 {claimId:'hypothesis.route.export',evidenceId:'artifact.route.audit',label:'Export → request_audit',note:'Action route_export связан с request id.'},
 {claimId:'outcome.route.timeline',evidenceId:'artifact.route.access',label:'Timeline → access.jsonl',note:'Порядок session_create, route_view и export восстановлен по времени.'},
];
const hints=['Начни с http list и открой login exchange. Зафиксируй Set-Cookie и request id.','Проверь sql tables и schema. Session creation и audit usage лежат в разных источниках.','Сравни created_ip с source_ip у route_export. HTTP 200 доказывает действие, но не кражу пароля.','В отчёте отдели session reuse, export и неизвестный способ получения session.'];
export function ChapterTwoRoute(){const runtime=useMissionRuntime();const mission=runtime.activeMission;const definition=getMissionDefinition('marshrut-investigation-01');const bundle=useMemo(()=>createMarshrutEnvironment(mission?.seed??1),[mission?.seed]);const[hint,setHint]=useState(0);const[reasons,setReasons]=useState<string[]>([]);if(!mission||mission.missionId!=='marshrut-investigation-01'||!definition)return <main className="chapter-two-loading">МАРШРУТ-01 не загружен.</main>;
 const complete=()=>{const r=runtime.completeActiveMission();setReasons(r.reasons)};
 if(mission.status==='completed')return <main className="chapter-two-complete"><section><ShieldCheck size={38}/><p className="eyebrow">АКТ 2 / СЛОЙ 1 ЗАКРЫТ</p><h1>Ночная сессия разобрана</h1><p>Session reuse и export подтверждены, password compromise не выдуман, границы передачи данных сохранены.</p><div className="chapter-two-score-grid"><article><span>CORRECTNESS</span><strong>{mission.assessment?.dimensionScores.correctness??0}</strong></article><article><span>EVIDENCE</span><strong>{mission.assessment?.dimensionScores.evidence??0}</strong></article><article><span>JUDGMENT</span><strong>{mission.assessment?.dimensionScores.judgment??0}</strong></article><article><span>HINT</span><strong>{mission.assessment?.autonomy.highestHintTier??0}/5</strong></article></div><button className="primary-action" onClick={()=>runtime.ensureMission('act2-contract-http')}>Перейти к контрактам <ArrowRight size={17}/></button></section></main>;
 return <main className="chapter-two-screen"><header className="chapter-two-header"><div><p className="eyebrow">АКТ 2 / МАРШРУТ / СЛОЙ 1</p><h1>{definition.title}</h1><p>{definition.briefing.objective}</p></div><div><button onClick={()=>{const n=Math.min(5,hint+1);setHint(n);runtime.recordHint(n,`route-hint-${n}`)}}><CircleHelp size={16}/>Подсказка {Math.min(5,hint+1)}/5</button><button onClick={runtime.resetActiveMission}><RotateCcw size={15}/>Reset</button></div></header>{hint>0&&<section className="chapter-two-hint"><strong>Игорь</strong><p>{hints[Math.min(hint-1,hints.length-1)]}</p></section>}<section className="chapter-two-layout"><div className="chapter-two-tools"><section className="chapter-two-model"><strong>Локальная модель</strong><p><code>http list</code>, <code>http show req-id</code>, <code>sql tables</code>, <code>sql schema table</code>. Только captured local data.</p></section><CaseShellPanel environment={bundle.shell} title="MARSHRUT LOCAL LAB"/></div><CaseReasoningPanel evidenceSuggestions={evidence}/></section><footer className="chapter-two-footer"><div><span>Evidence: {mission.evidenceLinks.length}/4</span><span>Hypotheses: {mission.hypotheses.length}/4</span></div><button className="primary-action" onClick={complete}>Проверить расследование</button>{reasons.length>0&&<p>Не закрыто: {reasons.join(' · ')}</p>}</footer></main>}
