import type { MissionDefinition } from '../../../core/scenario/types';

export const logs01Definition: MissionDefinition = {
  schemaVersion: 1,
  id: 'logs-01',
  chapterId: 'chapter-0.2',
  title: 'Глава 0.2 / Shell, логи и время',
  level: 'foundation',
  faction: 'independent',
  durationMinutes: 35,
  skills: [
    'shell.pipeline',
    'data.logs',
    'data.time-normalization',
    'data.jsonl',
    'analysis.evidence-basics',
  ],
  briefing: {
    summary: 'Максим открыл следующий набор CLINIC-01: auth.log, proxy.csv и независимый JSONL-пакет. Данные локальные и синтетические.',
    objective: 'Получить воспроизводимый счётчик отказов, определить источник, нормализовать время и самостоятельно разобрать изменённый JSONL-набор.',
    constraints: [
      'Исходные файлы read-only.',
      'Производные результаты сохраняются только в /home/ilya/work.',
      'Внешняя сеть отключена.',
      'Повреждённая строка не считается событием и не должна ломать весь анализ.',
      'Не объявлять успешный вход по строкам Failed password.',
    ],
    hiddenTruth: 'Guided-набор содержит шесть отказов с одного внешнего адреса. Transfer-набор меняет адрес, число событий, имя файла и добавляет повреждённую строку.',
  },
  artifacts: [
    {
      id: 'artifact.logs.intake',
      title: 'Передача главы 0.2',
      format: 'local-message',
      origin: 'Максим Белов',
      description: 'Цель, ограничения и границы локальной лаборатории.',
      containsNoise: false,
    },
    {
      id: 'artifact.logs.brief',
      title: 'brief.txt',
      format: 'text/plain',
      origin: 'CLINIC-01 / локальная копия',
      description: 'Рабочая задача, часовой пояс и требования к результату.',
      containsNoise: false,
    },
    {
      id: 'artifact.logs.formats',
      title: 'formats.txt',
      format: 'text/plain',
      origin: 'Локальная памятка форматов',
      description: 'Описание TXT, CSV, JSONL, stdout, stderr и exit code.',
      containsNoise: false,
    },
    {
      id: 'artifact.logs.auth',
      title: 'logs/auth.log',
      format: 'linux-auth-log',
      origin: 'clinic-ws / sshd',
      description: 'Guided-набор успешных и неуспешных входов.',
      containsNoise: true,
    },
    {
      id: 'artifact.logs.proxy',
      title: 'logs/proxy.csv',
      format: 'text/csv',
      origin: 'clinic proxy / UTC',
      description: 'Сетевые события с временными метками UTC.',
      containsNoise: true,
    },
    {
      id: 'artifact.logs.transfer',
      title: 'transfer/*.jsonl',
      format: 'application/x-jsonlines',
      origin: 'Второй локальный collector',
      description: 'Самостоятельный набор с другим источником, количеством событий и повреждённой строкой.',
      containsNoise: true,
    },
  ],
  outcomes: [
    {
      id: 'outcome.logs.pipeline',
      skillId: 'shell.pipeline',
      statement: 'Передаёт stdout между командами и различает результат, stderr и exit code.',
      evidenceType: 'guided',
      criticalErrors: ['Изменение исходного файла.', 'Обращение к внешней сети.'],
    },
    {
      id: 'outcome.logs.guided-count',
      skillId: 'data.logs',
      statement: 'Фильтрует auth.log и получает воспроизводимый счётчик событий отказа.',
      evidenceType: 'guided',
    },
    {
      id: 'outcome.logs.time',
      skillId: 'data.time-normalization',
      statement: 'Переводит локальную временную метку UTC+03:00 в UTC перед корреляцией с proxy.csv.',
      evidenceType: 'guided',
    },
    {
      id: 'outcome.logs.transfer',
      skillId: 'data.jsonl',
      statement: 'Самостоятельно обрабатывает изменённый JSONL-набор, исключает повреждённую строку и находит источник с количеством отказов.',
      evidenceType: 'transfer',
    },
    {
      id: 'outcome.logs.evidence',
      skillId: 'analysis.evidence-basics',
      statement: 'Связывает выводы с конкретными открытыми артефактами.',
      evidenceType: 'independent',
    },
  ],
  hypotheses: [],
  decisions: [],
  assessmentRules: [
    {
      id: 'rule.logs.started',
      title: 'Глава запущена через mission runtime',
      dimension: 'method',
      weight: 1,
      matcher: { kind: 'event', eventType: 'mission.started' },
    },
    {
      id: 'rule.logs.intake-opened',
      title: 'Ограничения главы приняты',
      dimension: 'method',
      weight: 1,
      matcher: {
        kind: 'event', eventType: 'artifact.opened',
        where: [{ path: 'payload.artifactId', operator: 'eq', value: 'artifact.logs.intake' }],
      },
    },
    {
      id: 'rule.logs.brief-opened',
      title: 'Рабочая задача и часовой пояс прочитаны',
      dimension: 'method',
      weight: 2,
      matcher: {
        kind: 'event', eventType: 'artifact.opened',
        where: [{ path: 'payload.artifactId', operator: 'eq', value: 'artifact.logs.brief' }],
      },
    },
    {
      id: 'rule.logs.formats-opened',
      title: 'Форматы данных проверены до transfer',
      dimension: 'coverage',
      weight: 1,
      matcher: {
        kind: 'event', eventType: 'artifact.opened',
        where: [{ path: 'payload.artifactId', operator: 'eq', value: 'artifact.logs.formats' }],
      },
    },
    {
      id: 'rule.logs.pipeline-used',
      title: 'stdout передан между командами',
      dimension: 'method',
      weight: 2,
      matcher: {
        kind: 'event', eventType: 'command.executed',
        where: [
          { path: 'payload.usedPipe', operator: 'eq', value: true },
          { path: 'payload.success', operator: 'eq', value: true },
        ],
      },
    },
    {
      id: 'rule.logs.guided-count',
      title: 'Получен воспроизводимый счётчик отказов',
      dimension: 'correctness',
      weight: 3,
      matcher: {
        kind: 'event', eventType: 'command.executed',
        where: [{ path: 'payload.finding', operator: 'eq', value: 'guided-failure-count' }],
      },
    },
    {
      id: 'rule.logs.guided-source',
      title: 'Внешний источник найден в auth.log',
      dimension: 'correctness',
      weight: 2,
      matcher: {
        kind: 'event', eventType: 'command.executed',
        where: [{ path: 'payload.finding', operator: 'eq', value: 'guided-source' }],
      },
    },
    {
      id: 'rule.logs.derived-output',
      title: 'Производный результат сохранён вне исходных данных',
      dimension: 'method',
      weight: 1,
      matcher: {
        kind: 'event', eventType: 'command.executed',
        where: [
          { path: 'payload.derivedWrite', operator: 'eq', value: true },
          { path: 'payload.success', operator: 'eq', value: true },
        ],
      },
    },
    {
      id: 'rule.logs.time-normalized',
      title: 'Локальное время переведено в UTC',
      dimension: 'correctness',
      weight: 3,
      matcher: {
        kind: 'event', eventType: 'command.executed',
        where: [{ path: 'payload.finding', operator: 'eq', value: 'normalized-time' }],
      },
    },
    {
      id: 'rule.logs.proxy-opened',
      title: 'UTC-результат сопоставлен с proxy.csv',
      dimension: 'coverage',
      weight: 2,
      matcher: {
        kind: 'event', eventType: 'artifact.opened',
        where: [{ path: 'payload.artifactId', operator: 'eq', value: 'artifact.logs.proxy' }],
      },
    },
    {
      id: 'rule.logs.transfer-opened',
      title: 'Самостоятельный JSONL-набор найден и открыт',
      dimension: 'coverage',
      weight: 2,
      matcher: {
        kind: 'event', eventType: 'artifact.opened',
        where: [{ path: 'payload.artifactId', operator: 'eq', value: 'artifact.logs.transfer' }],
      },
    },
    {
      id: 'rule.logs.transfer-result',
      title: 'Источник и число отказов получены из transfer-набора',
      dimension: 'correctness',
      weight: 4,
      matcher: {
        kind: 'event', eventType: 'command.executed',
        where: [{ path: 'payload.finding', operator: 'eq', value: 'transfer-source-count' }],
      },
    },
    {
      id: 'rule.logs.transfer-jq',
      title: 'JSONL разобран структурированным инструментом',
      dimension: 'efficiency',
      weight: 1,
      matcher: {
        kind: 'event', eventType: 'command.executed',
        where: [
          { path: 'payload.finding', operator: 'eq', value: 'transfer-source-count' },
          { path: 'payload.tools', operator: 'includes', value: 'jq' },
        ],
      },
    },
    {
      id: 'rule.logs.transfer-cut',
      title: 'JSONL разобран текстовым pipeline',
      dimension: 'efficiency',
      weight: 1,
      matcher: {
        kind: 'event', eventType: 'command.executed',
        where: [
          { path: 'payload.finding', operator: 'eq', value: 'transfer-source-count' },
          { path: 'payload.tools', operator: 'includes', value: 'cut' },
        ],
      },
    },
    {
      id: 'rule.logs.guided-evidence',
      title: 'Guided-вывод связан с auth.log',
      dimension: 'evidence',
      weight: 2,
      matcher: {
        kind: 'evidence-link',
        claimId: 'outcome.logs.guided-count',
        evidenceIds: ['artifact.logs.auth'],
      },
    },
    {
      id: 'rule.logs.time-evidence',
      title: 'Нормализация времени связана с proxy.csv',
      dimension: 'evidence',
      weight: 2,
      matcher: {
        kind: 'evidence-link',
        claimId: 'outcome.logs.time',
        evidenceIds: ['artifact.logs.proxy'],
      },
    },
    {
      id: 'rule.logs.transfer-evidence',
      title: 'Transfer-вывод связан с JSONL',
      dimension: 'evidence',
      weight: 3,
      matcher: {
        kind: 'evidence-link',
        claimId: 'outcome.logs.transfer',
        evidenceIds: ['artifact.logs.transfer'],
      },
    },
    {
      id: 'rule.logs.autonomy',
      title: 'Полный ответ не раскрыт подсказкой',
      dimension: 'autonomy',
      weight: 1,
      matcher: { kind: 'hint-ceiling', maxTier: 4 },
    },
    {
      id: 'critical.logs.destructive',
      title: 'Исходные файлы не изменялись',
      dimension: 'method',
      weight: 0,
      critical: true,
      matcher: {
        kind: 'event', eventType: 'command.executed',
        where: [{ path: 'payload.destructive', operator: 'eq', value: true }],
      },
    },
    {
      id: 'critical.logs.external-network',
      title: 'Внешняя сеть не использовалась',
      dimension: 'judgment',
      weight: 0,
      critical: true,
      matcher: {
        kind: 'event', eventType: 'command.executed',
        where: [{ path: 'payload.externalNetwork', operator: 'eq', value: true }],
      },
    },
  ],
  solutionFamilies: [
    {
      id: 'solution.logs.jq',
      title: 'Структурированный JSONL pipeline',
      description: 'Повреждённая строка отбрасывается, затем JSONL разбирается через jq, сортируется и группируется.',
      requiredRuleIds: ['rule.logs.transfer-jq'],
    },
    {
      id: 'solution.logs.text',
      title: 'Текстовый pipeline',
      description: 'Игрок извлекает поле из стабильного учебного формата через cut, затем сортирует и группирует.',
      requiredRuleIds: ['rule.logs.transfer-cut'],
    },
  ],
  completion: {
    coreRuleIds: [
      'rule.logs.started',
      'rule.logs.intake-opened',
      'rule.logs.brief-opened',
      'rule.logs.formats-opened',
      'rule.logs.pipeline-used',
      'rule.logs.guided-count',
      'rule.logs.guided-source',
      'rule.logs.derived-output',
      'rule.logs.time-normalized',
      'rule.logs.proxy-opened',
      'rule.logs.transfer-opened',
      'rule.logs.transfer-result',
      'rule.logs.guided-evidence',
      'rule.logs.time-evidence',
      'rule.logs.transfer-evidence',
    ],
    minDimensionScores: {
      correctness: 100,
      evidence: 100,
      method: 100,
      coverage: 100,
    },
  },
  consequences: [
    {
      id: 'consequence.logs.complete',
      trigger: 'success',
      summary: 'Shell, форматы и время подтверждены. CLINIC-01 переходит к процессам, автоматизации и гипотезам.',
      effects: { opensChapter03: true, professionalTrust: 1 },
    },
    {
      id: 'consequence.logs.destructive',
      trigger: 'critical-error',
      summary: 'Попытка изменить исходные данные требует reset главы.',
      effects: { requiresReset: true },
    },
  ],
  replay: {
    seeded: true,
    variables: [
      'transfer-source',
      'transfer-failure-count',
      'transfer-file-name',
      'event-order',
      'damaged-line-position',
    ],
  },
  safety: {
    sandboxed: true,
    externalNetwork: false,
    allowedActions: [
      'read-local-file',
      'filter-local-log',
      'pipe-local-output',
      'write-derived-output',
      'normalize-local-time',
      'parse-local-jsonl',
      'link-evidence',
    ],
    resettable: true,
  },
};
