import type { MissionDefinition } from '../../../core/scenario/types';

export const clinic01Definition: MissionDefinition = {
  schemaVersion: 1,
  id: 'clinic-01',
  chapterId: 'chapter-0.3',
  title: 'CLINIC-01 / Компьютер регистратуры',
  level: 'foundation',
  faction: 'independent',
  durationMinutes: 55,
  skills: [
    'computing.filesystem',
    'shell.linux-basics',
    'data.logs',
    'analysis.hypothesis',
    'reporting.evidence',
  ],
  briefing: {
    summary: 'Регистратура жалуется на тормоза. Ночью зафиксированы попытки входа. Максим передал очищенную локальную копию данных.',
    objective: 'Установить подтверждённые события, проверить подозрительный процесс и предложить безопасное первое действие.',
    constraints: [
      'Работать только с локальной копией.',
      'Не удалять данные до фиксации evidence.',
      'Не объявлять компрометацию без подтверждённого успешного доступа.',
    ],
    hiddenTruth: 'Внешний password spray не дал успешного входа. Отдельный локальный процесс требует проверки, но его происхождение первым набором данных не доказано.',
  },
  artifacts: [
    {
      id: 'artifact.clinic.brief',
      title: 'brief.txt',
      format: 'text/plain',
      origin: 'Максим Белов / локальная копия',
      description: 'Постановка задачи и ограничения.',
      containsNoise: false,
    },
    {
      id: 'artifact.clinic.auth-log',
      title: 'auth.log',
      format: 'linux-auth-log',
      origin: 'clinic-ws / sshd',
      description: 'События успешных и неуспешных SSH-входов.',
      containsNoise: true,
    },
    {
      id: 'artifact.clinic.processes',
      title: 'processes.txt',
      format: 'process-list',
      origin: 'clinic-ws / process snapshot',
      description: 'Снимок процессов с PID, пользователем и командной строкой.',
      containsNoise: true,
    },
    {
      id: 'artifact.clinic.network',
      title: 'network.txt',
      format: 'asset-map',
      origin: 'clinic-ws / local inventory',
      description: 'Локальные адреса узлов, доступные в первом наборе данных.',
      containsNoise: false,
    },
  ],
  outcomes: [
    {
      id: 'outcome.clinic.navigate',
      skillId: 'computing.filesystem',
      statement: 'Самостоятельно находит материалы дела и различает файл, каталог, относительный и абсолютный путь.',
      evidenceType: 'independent',
    },
    {
      id: 'outcome.clinic.filter-log',
      skillId: 'shell.linux-basics',
      statement: 'Выбирает read-only команды для фильтрации журнала и получает воспроизводимый результат.',
      evidenceType: 'independent',
      criticalErrors: ['Удаление или изменение исходного журнала.'],
    },
    {
      id: 'outcome.clinic.reason',
      skillId: 'analysis.hypothesis',
      statement: 'Отделяет password spray от доказанной компрометации и сохраняет неопределённость по процессу.',
      evidenceType: 'transfer',
    },
    {
      id: 'outcome.clinic.report',
      skillId: 'reporting.evidence',
      statement: 'Связывает выводы с evidence, указывает ограничения и безопасное следующее действие.',
      evidenceType: 'independent',
    },
  ],
  hypotheses: [
    {
      id: 'hypothesis.clinic.password-spray',
      title: 'Внешний password spray',
      description: 'Серия неудачных попыток входа с одного внешнего источника.',
      allowedStatuses: ['open', 'supported', 'rejected', 'unknown'],
    },
    {
      id: 'hypothesis.clinic.account-compromise',
      title: 'Компрометация учётной записи',
      description: 'Внешний источник получил успешную сессию.',
      allowedStatuses: ['open', 'supported', 'rejected', 'unknown'],
    },
    {
      id: 'hypothesis.clinic.local-process',
      title: 'Подозрительный локальный процесс',
      description: 'Процесс из временного каталога требует отдельного происхождения и runtime-проверки.',
      allowedStatuses: ['open', 'supported', 'rejected', 'unknown'],
    },
  ],
  decisions: [
    {
      id: 'decision.clinic.preserve-restrict',
      title: 'Сохранить данные и ограничить внешний SSH',
      description: 'Фиксировать артефакты, ограничить удалённый вход и отдельно исследовать PID без остановки регистратуры.',
      risk: 'low',
    },
    {
      id: 'decision.clinic.isolate-transfer',
      title: 'Изолировать станцию и перевести работу на резерв',
      description: 'Изолировать узел, если клиника подтверждает готовность резервного места, сохранив volatile evidence.',
      risk: 'medium',
    },
  ],
  assessmentRules: [
    {
      id: 'rule.clinic.started',
      title: 'Миссия запущена через runtime',
      dimension: 'method',
      weight: 1,
      matcher: { kind: 'event', eventType: 'mission.started' },
    },
    {
      id: 'rule.clinic.brief-opened',
      title: 'Ограничения прочитаны до решения',
      dimension: 'method',
      weight: 2,
      matcher: {
        kind: 'event',
        eventType: 'artifact.opened',
        where: [{ path: 'payload.artifactId', operator: 'eq', value: 'artifact.clinic.brief' }],
      },
    },
    {
      id: 'rule.clinic.auth-inspected',
      title: 'Журнал входов исследован инструментом',
      dimension: 'method',
      weight: 3,
      matcher: {
        kind: 'event',
        eventType: 'command.executed',
        where: [
          { path: 'payload.readOnly', operator: 'eq', value: true },
          { path: 'payload.targetArtifactId', operator: 'eq', value: 'artifact.clinic.auth-log' },
          { path: 'payload.success', operator: 'eq', value: true },
        ],
      },
    },
    {
      id: 'rule.clinic.process-inspected',
      title: 'Процессы исследованы отдельно от auth-событий',
      dimension: 'coverage',
      weight: 3,
      matcher: {
        kind: 'event',
        eventType: 'command.executed',
        where: [
          { path: 'payload.targetArtifactId', operator: 'eq', value: 'artifact.clinic.processes' },
          { path: 'payload.success', operator: 'eq', value: true },
        ],
      },
    },
    {
      id: 'rule.clinic.spray-hypothesis',
      title: 'Password spray поддержан, а не угадан',
      dimension: 'correctness',
      weight: 3,
      matcher: {
        kind: 'hypothesis',
        hypothesisId: 'hypothesis.clinic.password-spray',
        statuses: ['supported'],
      },
    },
    {
      id: 'rule.clinic.compromise-not-overstated',
      title: 'Успешная внешняя компрометация не объявлена без данных',
      dimension: 'judgment',
      weight: 3,
      matcher: {
        kind: 'hypothesis',
        hypothesisId: 'hypothesis.clinic.account-compromise',
        statuses: ['rejected', 'unknown'],
      },
    },
    {
      id: 'rule.clinic.spray-evidence',
      title: 'Вывод о password spray связан с auth.log',
      dimension: 'evidence',
      weight: 3,
      matcher: {
        kind: 'evidence-link',
        claimId: 'hypothesis.clinic.password-spray',
        evidenceIds: ['artifact.clinic.auth-log'],
        minLinks: 1,
      },
    },
    {
      id: 'rule.clinic.process-evidence',
      title: 'Вывод о процессе связан со снимком процессов',
      dimension: 'evidence',
      weight: 2,
      matcher: {
        kind: 'evidence-link',
        claimId: 'hypothesis.clinic.local-process',
        evidenceIds: ['artifact.clinic.processes'],
        minLinks: 1,
      },
    },
    {
      id: 'rule.clinic.report',
      title: 'Отчёт содержит факт, evidence, ограничение и действие',
      dimension: 'communication',
      weight: 3,
      matcher: {
        kind: 'report',
        requiredSections: ['facts', 'evidence', 'limitations', 'decision', 'nextSteps'],
      },
    },
    {
      id: 'rule.clinic.decision-preserve',
      title: 'Выбран осторожный путь сохранения evidence',
      dimension: 'judgment',
      weight: 1,
      matcher: { kind: 'decision', decisionIds: ['decision.clinic.preserve-restrict'] },
    },
    {
      id: 'rule.clinic.decision-isolate',
      title: 'Выбран путь изоляции с переводом работы',
      dimension: 'judgment',
      weight: 1,
      matcher: { kind: 'decision', decisionIds: ['decision.clinic.isolate-transfer'] },
    },
    {
      id: 'rule.clinic.autonomy',
      title: 'Самостоятельный уровень подсказок',
      dimension: 'autonomy',
      weight: 1,
      matcher: { kind: 'hint-ceiling', maxTier: 3 },
    },
    {
      id: 'critical.clinic.destructive-action',
      title: 'Исходные данные не изменены и не удалены',
      dimension: 'method',
      weight: 0,
      critical: true,
      matcher: {
        kind: 'event',
        eventType: 'command.executed',
        where: [{ path: 'payload.destructive', operator: 'eq', value: true }],
      },
    },
    {
      id: 'critical.clinic.external-network',
      title: 'Нет обращения к внешней сети',
      dimension: 'judgment',
      weight: 0,
      critical: true,
      matcher: {
        kind: 'event',
        eventType: 'command.executed',
        where: [{ path: 'payload.externalNetwork', operator: 'eq', value: true }],
      },
    },
  ],
  solutionFamilies: [
    {
      id: 'solution.clinic.preserve-restrict',
      title: 'Сохранить evidence и ограничить внешний доступ',
      description: 'Минимальное влияние на клинику при сохранении возможности дальнейшего анализа.',
      requiredRuleIds: ['rule.clinic.decision-preserve'],
    },
    {
      id: 'solution.clinic.isolate-transfer',
      title: 'Изолировать узел и перевести регистратуру на резерв',
      description: 'Более жёсткое действие, допустимое при сохранении данных и наличии рабочего резерва.',
      requiredRuleIds: ['rule.clinic.decision-isolate'],
    },
  ],
  completion: {
    coreRuleIds: [
      'rule.clinic.started',
      'rule.clinic.brief-opened',
      'rule.clinic.auth-inspected',
      'rule.clinic.process-inspected',
      'rule.clinic.spray-hypothesis',
      'rule.clinic.compromise-not-overstated',
      'rule.clinic.spray-evidence',
      'rule.clinic.process-evidence',
      'rule.clinic.report',
    ],
    minDimensionScores: {
      correctness: 100,
      evidence: 100,
      method: 100,
      coverage: 100,
      communication: 100,
      judgment: 75,
    },
  },
  consequences: [
    {
      id: 'consequence.clinic.clean',
      trigger: 'success',
      summary: 'Максим получает воспроизводимый отчёт и передаёт его Анне.',
      effects: { professionalTrust: 2, opensInterview: true },
    },
    {
      id: 'consequence.clinic.destroyed-evidence',
      trigger: 'critical-error',
      summary: 'Исходные данные повреждены. Требуется восстановительная учебная миссия.',
      effects: { professionalTrust: -2, opensRemedialMission: true },
    },
    {
      id: 'consequence.clinic.isolation',
      trigger: 'decision',
      decisionId: 'decision.clinic.isolate-transfer',
      summary: 'Клиника переводит регистратуру на резерв. Работа замедляется, но узел отделён.',
      effects: { downtime: 1, containment: 2 },
    },
  ],
  replay: {
    seeded: true,
    variables: [
      'event-order',
      'external-source',
      'failed-account-set',
      'legitimate-process-noise',
      'missing-log-window',
      'reserve-workstation-availability',
    ],
  },
  safety: {
    sandboxed: true,
    externalNetwork: false,
    allowedActions: ['read-local-file', 'filter-local-log', 'run-sandboxed-python', 'link-evidence', 'submit-local-report'],
    resettable: true,
  },
};
