import type { MissionDefinition } from '../../../core/scenario/types';

export const clinic01Definition: MissionDefinition = {
  schemaVersion: 1,
  id: 'clinic-01',
  chapterId: 'chapter-0.3',
  title: 'CLINIC-01 / Компьютер регистратуры',
  level: 'foundation',
  faction: 'independent',
  durationMinutes: 70,
  skills: [
    'analysis.process-correlation',
    'analysis.network-correlation',
    'python.log-analysis',
    'analysis.hypothesis',
    'reporting.evidence',
    'incident.initial-response',
  ],
  briefing: {
    summary: 'Регистратура тормозит. Внешний password spray уже подтверждён в главе 0.2. Теперь нужно проверить локальные процессы и соединения.',
    objective: 'Разделить независимые события, написать переносимый Python-анализатор, сформировать гипотезы и выбрать безопасное действие.',
    constraints: [
      'Только локальная очищенная копия.',
      'Нельзя изменять исходные артефакты.',
      'Нельзя связывать события только потому, что они выглядят подозрительно.',
      'Python должен пройти видимый и скрытый набор.',
    ],
    hiddenTruth: 'Password spray не дал внешней успешной сессии. Процесс из /tmp установил внешнее соединение, но причинная связь со spray не подтверждена.',
  },
  artifacts: [
    { id: 'artifact.clinic.brief', title: 'brief.txt', format: 'text/plain', origin: 'Максим / локальная передача', description: 'Условия CLINIC-01.', containsNoise: false },
    { id: 'artifact.clinic.auth-log', title: 'auth.log', format: 'linux-auth-log', origin: 'clinic-ws / sshd', description: 'Входы и отказы.', containsNoise: true },
    { id: 'artifact.clinic.processes', title: 'processes.csv', format: 'csv/process-snapshot', origin: 'clinic-ws / snapshot', description: 'PID, PPID, пользователь, путь и аргументы.', containsNoise: true },
    { id: 'artifact.clinic.network', title: 'connections.csv', format: 'csv/socket-snapshot', origin: 'clinic-ws / socket snapshot', description: 'PID и сетевые соединения.', containsNoise: true },
    { id: 'artifact.clinic.events', title: 'events.jsonl', format: 'jsonl', origin: 'collector / normalized copy', description: 'Набор для переносимого Python-анализатора.', containsNoise: true },
  ],
  outcomes: [
    { id: 'outcome.clinic.process', skillId: 'analysis.process-correlation', statement: 'Связывает PID, PPID, пользователя, путь и аргументы.', evidenceType: 'guided' },
    { id: 'outcome.clinic.network', skillId: 'analysis.network-correlation', statement: 'Связывает процесс с внешним соединением по PID.', evidenceType: 'guided' },
    { id: 'outcome.clinic.python', skillId: 'python.log-analysis', statement: 'Пишет analyze(path), проходящий visible и hidden datasets.', evidenceType: 'independent' },
    { id: 'outcome.clinic.reason', skillId: 'analysis.hypothesis', statement: 'Отделяет подтверждённые события от недоказанной причинной связи.', evidenceType: 'independent' },
    { id: 'outcome.clinic.report', skillId: 'reporting.evidence', statement: 'Пишет воспроизводимый отчёт с фактами, evidence, ограничениями и действием.', evidenceType: 'independent' },
    { id: 'outcome.clinic.response', skillId: 'incident.initial-response', statement: 'Выбирает допустимый containment с учётом работы клиники.', evidenceType: 'guided' },
  ],
  hypotheses: [
    { id: 'hypothesis.clinic.password-spray', title: 'Внешний password spray', description: 'Серия неудачных входов с одного внешнего адреса.', allowedStatuses: ['open', 'supported', 'rejected', 'unknown'] },
    { id: 'hypothesis.clinic.account-compromise', title: 'Внешняя успешная сессия', description: 'Внешний источник получил успешный доступ.', allowedStatuses: ['open', 'supported', 'rejected', 'unknown'] },
    { id: 'hypothesis.clinic.local-process', title: 'Подозрительный локальный процесс', description: 'Процесс из временного каталога установил внешнее соединение.', allowedStatuses: ['open', 'supported', 'rejected', 'unknown'] },
    { id: 'hypothesis.clinic.shared-cause', title: 'Spray и процесс имеют общую причину', description: 'Два наблюдения являются одной цепочкой атаки.', allowedStatuses: ['open', 'supported', 'rejected', 'unknown'] },
  ],
  decisions: [
    { id: 'decision.clinic.preserve-restrict', title: 'Сохранить данные и ограничить SSH', description: 'Сохранить артефакты, ограничить внешний SSH, проверить процесс отдельно.', risk: 'low' },
    { id: 'decision.clinic.isolate-transfer', title: 'Изолировать узел и включить резерв', description: 'Сохранить volatile data, изолировать узел, перевести регистратуру на резерв.', risk: 'medium' },
    { id: 'decision.clinic.observe-only', title: 'Продолжить наблюдение без ограничений', description: 'Оставить внешний SSH и процесс без containment.', risk: 'high' },
  ],
  assessmentRules: [
    { id: 'rule.clinic.started', title: 'Миссия запущена', dimension: 'method', weight: 1, matcher: { kind: 'event', eventType: 'mission.started' } },
    { id: 'rule.clinic.brief', title: 'Brief открыт', dimension: 'method', weight: 1, matcher: { kind: 'event', eventType: 'artifact.opened', where: [{ path: 'payload.artifactId', operator: 'eq', value: 'artifact.clinic.brief' }] } },
    { id: 'rule.clinic.process', title: 'Процесс найден инструментом', dimension: 'coverage', weight: 3, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'clinic-process-correlated' }] } },
    { id: 'rule.clinic.network', title: 'Соединение связано с PID', dimension: 'coverage', weight: 3, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'clinic-network-correlated' }] } },
    { id: 'rule.clinic.python', title: 'Python прошёл hidden tests', dimension: 'correctness', weight: 4, matcher: { kind: 'event', eventType: 'python.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'clinic-python-hidden-tests' }, { path: 'payload.success', operator: 'eq', value: true }] } },
    { id: 'rule.clinic.spray', title: 'Spray поддержан', dimension: 'correctness', weight: 2, matcher: { kind: 'hypothesis', hypothesisId: 'hypothesis.clinic.password-spray', statuses: ['supported'] } },
    { id: 'rule.clinic.no-compromise', title: 'Внешний успех не выдуман', dimension: 'judgment', weight: 3, matcher: { kind: 'hypothesis', hypothesisId: 'hypothesis.clinic.account-compromise', statuses: ['rejected', 'unknown'] } },
    { id: 'rule.clinic.local-process', title: 'Локальный процесс поддержан', dimension: 'correctness', weight: 2, matcher: { kind: 'hypothesis', hypothesisId: 'hypothesis.clinic.local-process', statuses: ['supported'] } },
    { id: 'rule.clinic.no-false-link', title: 'Причинная связь не выдумана', dimension: 'judgment', weight: 3, matcher: { kind: 'hypothesis', hypothesisId: 'hypothesis.clinic.shared-cause', statuses: ['rejected', 'unknown'] } },
    { id: 'rule.clinic.spray-evidence', title: 'Spray связан с auth.log', dimension: 'evidence', weight: 2, matcher: { kind: 'evidence-link', claimId: 'hypothesis.clinic.password-spray', evidenceIds: ['artifact.clinic.auth-log'] } },
    { id: 'rule.clinic.process-evidence', title: 'Процесс связан со snapshot', dimension: 'evidence', weight: 2, matcher: { kind: 'evidence-link', claimId: 'hypothesis.clinic.local-process', evidenceIds: ['artifact.clinic.processes'] } },
    { id: 'rule.clinic.network-evidence', title: 'Сеть связана с connections', dimension: 'evidence', weight: 2, matcher: { kind: 'evidence-link', claimId: 'outcome.clinic.network', evidenceIds: ['artifact.clinic.network'] } },
    { id: 'rule.clinic.python-evidence', title: 'Python связан с JSONL', dimension: 'evidence', weight: 2, matcher: { kind: 'evidence-link', claimId: 'outcome.clinic.python', evidenceIds: ['artifact.clinic.events'] } },
    { id: 'rule.clinic.report', title: 'Отчёт полный', dimension: 'communication', weight: 4, matcher: { kind: 'report', requiredSections: ['facts', 'evidence', 'limitations', 'decision', 'nextSteps'] } },
    { id: 'rule.clinic.autonomy', title: 'Подсказки не раскрыли полный метод', dimension: 'autonomy', weight: 1, matcher: { kind: 'hint-ceiling', maxTier: 3 } },
    { id: 'rule.clinic.preserve', title: 'Осторожный containment', dimension: 'judgment', weight: 1, matcher: { kind: 'decision', decisionIds: ['decision.clinic.preserve-restrict'] } },
    { id: 'rule.clinic.isolate', title: 'Изоляция с резервом', dimension: 'judgment', weight: 1, matcher: { kind: 'decision', decisionIds: ['decision.clinic.isolate-transfer'] } },
    { id: 'critical.clinic.observe', title: 'Не оставлять риск без containment', dimension: 'judgment', weight: 0, critical: true, matcher: { kind: 'decision', decisionIds: ['decision.clinic.observe-only'] } },
    { id: 'critical.clinic.destructive', title: 'Не уничтожать evidence', dimension: 'method', weight: 0, critical: true, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.destructive', operator: 'eq', value: true }] } },
    { id: 'critical.clinic.network-call', title: 'Нет внешних обращений', dimension: 'judgment', weight: 0, critical: true, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.externalNetwork', operator: 'eq', value: true }] } },
  ],
  solutionFamilies: [
    { id: 'solution.clinic.preserve', title: 'Сохранить и ограничить', description: 'Минимальный простой, сохранение evidence и ограничение SSH.', requiredRuleIds: ['rule.clinic.preserve'] },
    { id: 'solution.clinic.isolate', title: 'Изолировать с резервом', description: 'Изоляция при наличии резервного рабочего места.', requiredRuleIds: ['rule.clinic.isolate'] },
  ],
  completion: {
    coreRuleIds: ['rule.clinic.started', 'rule.clinic.brief', 'rule.clinic.process', 'rule.clinic.network', 'rule.clinic.python', 'rule.clinic.spray', 'rule.clinic.no-compromise', 'rule.clinic.local-process', 'rule.clinic.no-false-link', 'rule.clinic.spray-evidence', 'rule.clinic.process-evidence', 'rule.clinic.network-evidence', 'rule.clinic.python-evidence', 'rule.clinic.report'],
    minDimensionScores: { correctness: 100, evidence: 100, coverage: 100, communication: 100, judgment: 80 },
  },
  consequences: [
    { id: 'consequence.clinic.complete', trigger: 'success', summary: 'Максим передаёт отчёт Анне. Открывается самостоятельный пул контрактов.', effects: { opensAct0Contracts: true, professionalTrust: 2 } },
    { id: 'consequence.clinic.isolate', trigger: 'decision', decisionId: 'decision.clinic.isolate-transfer', summary: 'Регистратура работает через резерв.', effects: { downtime: 1, containment: 2 } },
    { id: 'consequence.clinic.observe', trigger: 'critical-error', summary: 'Риск оставлен без контроля. Требуется reset решения.', effects: { requiresReset: true } },
  ],
  replay: { seeded: true, variables: ['external-source', 'failure-count', 'suspicious-pid', 'remote-ip', 'event-order', 'hidden-dataset'] },
  safety: { sandboxed: true, externalNetwork: false, allowedActions: ['read-local-file', 'inspect-process-snapshot', 'inspect-socket-snapshot', 'run-sandboxed-python', 'link-evidence', 'submit-local-report'], resettable: true },
};
