import type { MissionDefinition } from '../../../core/scenario/types';

export const sferaOrientation01Definition: MissionDefinition = {
  schemaVersion: 1,
  id: 'sfera-orientation-01',
  chapterId: 'chapter-1.1',
  title: 'СФЕРА-01 / Очередь первой линии',
  level: 'junior',
  faction: 'sfera',
  durationMinutes: 80,
  skills: [
    'soc.telemetry',
    'soc.triage',
    'analysis.scope',
    'endpoint.process-chain',
    'network.dns-analysis',
    'communication.handoff',
    'incident.initial-response',
  ],
  briefing: {
    summary: 'Анна вместо школьного собеседования даёт копию реальной очереди: письмо, endpoint и DNS. Кирилл помогает только с моделью работы.',
    objective: 'Разобрать три связанных сигнала, подтвердить факты по сырым данным, определить scope и подготовить безопасный handoff второй линии.',
    constraints: [
      'Работа только с локальной копией telemetry.',
      'Alert не считается доказанным incident.',
      'Нельзя удалять письмо, процесс или журналы до сохранения evidence.',
      'Нельзя утверждать компрометацию учётки без auth/session telemetry.',
    ],
    hiddenTruth: 'Письмо доставлено одному пользователю. WINWORD запустил PowerShell на ACC-WS-07, затем этот же хост начал регулярные DNS-запросы. Успешная внешняя сессия пользователя не подтверждена.',
  },
  artifacts: [
    { id: 'artifact.sfera.brief', title: 'shift-brief.txt', format: 'text/plain', origin: 'Анна Соколова', description: 'Условия учебной смены.', containsNoise: false },
    { id: 'artifact.sfera.alerts', title: 'alerts.jsonl', format: 'jsonl/siem-alerts', origin: 'WATCHTOWER SIEM', description: 'Очередь сигналов разных источников.', containsNoise: true },
    { id: 'artifact.sfera.mail', title: 'salary_update.eml', format: 'message/rfc822', origin: 'Mail Gateway', description: 'Сырое письмо и результаты аутентификации домена.', containsNoise: true },
    { id: 'artifact.sfera.processes', title: 'processes.csv', format: 'csv/process-tree', origin: 'Endpoint telemetry', description: 'Родительские процессы, командные строки и пользователи.', containsNoise: true },
    { id: 'artifact.sfera.dns', title: 'dns.log', format: 'dns-telemetry', origin: 'DNS resolver', description: 'Запросы рабочих станций.', containsNoise: true },
    { id: 'artifact.sfera.assets', title: 'assets.csv', format: 'csv/asset-inventory', origin: 'CMDB', description: 'Владельцы и критичность узлов.', containsNoise: false },
    { id: 'artifact.sfera.auth', title: 'identity.log', format: 'identity-telemetry', origin: 'Identity provider', description: 'Сессии пользователя и результаты MFA.', containsNoise: true },
  ],
  outcomes: [
    { id: 'outcome.sfera.queue', skillId: 'soc.telemetry', statement: 'Открывает alert и возвращается к исходному источнику.', evidenceType: 'guided' },
    { id: 'outcome.sfera.mail', skillId: 'soc.triage', statement: 'Подтверждает несовпадение домена и сохраняет письмо.', evidenceType: 'guided' },
    { id: 'outcome.sfera.endpoint', skillId: 'endpoint.process-chain', statement: 'Связывает WINWORD, PowerShell, пользователя и хост.', evidenceType: 'guided' },
    { id: 'outcome.sfera.dns', skillId: 'network.dns-analysis', statement: 'Находит регулярные DNS-запросы того же хоста.', evidenceType: 'guided' },
    { id: 'outcome.sfera.scope', skillId: 'analysis.scope', statement: 'Отделяет подтверждённый узел от неподтверждённой компрометации учётки.', evidenceType: 'independent' },
    { id: 'outcome.sfera.handoff', skillId: 'communication.handoff', statement: 'Собирает воспроизводимый handoff второй линии.', evidenceType: 'independent' },
    { id: 'outcome.sfera.response', skillId: 'incident.initial-response', statement: 'Выбирает containment с сохранением evidence и учётом работы пользователя.', evidenceType: 'guided' },
  ],
  hypotheses: [
    { id: 'hypothesis.sfera.phishing', title: 'Подозрительное письмо доставлено', description: 'Письмо пришло с чужого домена и содержит macro-enabled вложение.', allowedStatuses: ['open', 'supported', 'rejected', 'unknown'] },
    { id: 'hypothesis.sfera.execution', title: 'Документ запустил PowerShell', description: 'Process telemetry подтверждает цепочку WINWORD → PowerShell.', allowedStatuses: ['open', 'supported', 'rejected', 'unknown'] },
    { id: 'hypothesis.sfera.beacon', title: 'ACC-WS-07 делает регулярные DNS-запросы', description: 'Один хост повторяет запросы к внешнему домену.', allowedStatuses: ['open', 'supported', 'rejected', 'unknown'] },
    { id: 'hypothesis.sfera.account', title: 'Учётная запись пользователя скомпрометирована', description: 'Внешний источник получил новую успешную сессию пользователя.', allowedStatuses: ['open', 'supported', 'rejected', 'unknown'] },
  ],
  decisions: [
    { id: 'decision.sfera.isolate-preserve', title: 'Изолировать ACC-WS-07 и сохранить evidence', description: 'Изолировать endpoint через EDR, сохранить письмо, process telemetry и DNS, проверить сессии пользователя.', risk: 'low' },
    { id: 'decision.sfera.block-collect', title: 'Блокировать домен и собрать endpoint evidence', description: 'Блокировать домен и письмо, ограничить связь процесса, затем передать узел второй линии без удаления артефактов.', risk: 'medium' },
    { id: 'decision.sfera.delete-close', title: 'Удалить письмо и закрыть все сигналы', description: 'Удалить письмо, не сохранять telemetry и считать очередь очищенной.', risk: 'high' },
  ],
  assessmentRules: [
    { id: 'rule.sfera.started', title: 'Миссия запущена', dimension: 'method', weight: 1, matcher: { kind: 'event', eventType: 'mission.started' } },
    { id: 'rule.sfera.queue-mail', title: 'Mail alert открыт', dimension: 'method', weight: 1, matcher: { kind: 'event', eventType: 'query.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'sfera-queue-mail' }] } },
    { id: 'rule.sfera.queue-endpoint', title: 'Endpoint alert открыт', dimension: 'method', weight: 1, matcher: { kind: 'event', eventType: 'query.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'sfera-queue-endpoint' }] } },
    { id: 'rule.sfera.queue-dns', title: 'DNS alert открыт', dimension: 'method', weight: 1, matcher: { kind: 'event', eventType: 'query.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'sfera-queue-dns' }] } },
    { id: 'rule.sfera.mail', title: 'Письмо проверено по raw source', dimension: 'correctness', weight: 3, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'sfera-mail-domain' }] } },
    { id: 'rule.sfera.process', title: 'Process chain восстановлена', dimension: 'correctness', weight: 4, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'sfera-process-chain' }] } },
    { id: 'rule.sfera.dns', title: 'DNS-ритм подтверждён', dimension: 'correctness', weight: 3, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'sfera-dns-beacon' }] } },
    { id: 'rule.sfera.scope', title: 'Scope привязан к ACC-WS-07', dimension: 'coverage', weight: 3, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.finding', operator: 'eq', value: 'sfera-scope-host' }] } },
    { id: 'rule.sfera.phishing-hypothesis', title: 'Phishing поддержан', dimension: 'judgment', weight: 2, matcher: { kind: 'hypothesis', hypothesisId: 'hypothesis.sfera.phishing', statuses: ['supported'] } },
    { id: 'rule.sfera.execution-hypothesis', title: 'Execution поддержан', dimension: 'judgment', weight: 2, matcher: { kind: 'hypothesis', hypothesisId: 'hypothesis.sfera.execution', statuses: ['supported'] } },
    { id: 'rule.sfera.beacon-hypothesis', title: 'DNS activity поддержана', dimension: 'judgment', weight: 2, matcher: { kind: 'hypothesis', hypothesisId: 'hypothesis.sfera.beacon', statuses: ['supported'] } },
    { id: 'rule.sfera.account-hypothesis', title: 'Account compromise не выдуман', dimension: 'judgment', weight: 3, matcher: { kind: 'hypothesis', hypothesisId: 'hypothesis.sfera.account', statuses: ['rejected', 'unknown'] } },
    { id: 'rule.sfera.mail-evidence', title: 'Письмо связано с phishing', dimension: 'evidence', weight: 2, matcher: { kind: 'evidence-link', claimId: 'hypothesis.sfera.phishing', evidenceIds: ['artifact.sfera.mail'] } },
    { id: 'rule.sfera.process-evidence', title: 'Process snapshot связан с execution', dimension: 'evidence', weight: 2, matcher: { kind: 'evidence-link', claimId: 'hypothesis.sfera.execution', evidenceIds: ['artifact.sfera.processes'] } },
    { id: 'rule.sfera.dns-evidence', title: 'DNS связан с beacon', dimension: 'evidence', weight: 2, matcher: { kind: 'evidence-link', claimId: 'hypothesis.sfera.beacon', evidenceIds: ['artifact.sfera.dns'] } },
    { id: 'rule.sfera.scope-evidence', title: 'CMDB связан со scope', dimension: 'evidence', weight: 2, matcher: { kind: 'evidence-link', claimId: 'outcome.sfera.scope', evidenceIds: ['artifact.sfera.assets'] } },
    { id: 'rule.sfera.report', title: 'Handoff заполнен', dimension: 'communication', weight: 4, matcher: { kind: 'report', requiredSections: ['facts', 'evidence', 'limitations', 'decision', 'nextSteps'] } },
    { id: 'rule.sfera.autonomy', title: 'Подсказки не раскрыли всё решение', dimension: 'autonomy', weight: 1, matcher: { kind: 'hint-ceiling', maxTier: 4 } },
    { id: 'rule.sfera.isolate', title: 'Изоляция и сохранение', dimension: 'judgment', weight: 1, matcher: { kind: 'decision', decisionIds: ['decision.sfera.isolate-preserve'] } },
    { id: 'rule.sfera.block', title: 'Блокировка и сбор evidence', dimension: 'judgment', weight: 1, matcher: { kind: 'decision', decisionIds: ['decision.sfera.block-collect'] } },
    { id: 'critical.sfera.delete', title: 'Evidence не уничтожен', dimension: 'method', weight: 0, critical: true, matcher: { kind: 'decision', decisionIds: ['decision.sfera.delete-close'] } },
    { id: 'critical.sfera.destructive', title: 'Нет destructive-команд', dimension: 'method', weight: 0, critical: true, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.destructive', operator: 'eq', value: true }] } },
    { id: 'critical.sfera.network', title: 'Нет внешних обращений', dimension: 'judgment', weight: 0, critical: true, matcher: { kind: 'event', eventType: 'command.executed', where: [{ path: 'payload.externalNetwork', operator: 'eq', value: true }] } },
  ],
  solutionFamilies: [
    { id: 'solution.sfera.isolate', title: 'Изоляция endpoint', description: 'Сохранить evidence и изолировать подтверждённый узел.', requiredRuleIds: ['rule.sfera.isolate'] },
    { id: 'solution.sfera.block', title: 'Точечная блокировка и сбор', description: 'Ограничить связь и быстро передать полный evidence package.', requiredRuleIds: ['rule.sfera.block'] },
  ],
  completion: {
    coreRuleIds: [
      'rule.sfera.started', 'rule.sfera.queue-mail', 'rule.sfera.queue-endpoint', 'rule.sfera.queue-dns',
      'rule.sfera.mail', 'rule.sfera.process', 'rule.sfera.dns', 'rule.sfera.scope',
      'rule.sfera.phishing-hypothesis', 'rule.sfera.execution-hypothesis', 'rule.sfera.beacon-hypothesis', 'rule.sfera.account-hypothesis',
      'rule.sfera.mail-evidence', 'rule.sfera.process-evidence', 'rule.sfera.dns-evidence', 'rule.sfera.scope-evidence', 'rule.sfera.report',
    ],
    minDimensionScores: { correctness: 100, evidence: 100, method: 100, coverage: 100, communication: 100, judgment: 80 },
  },
  consequences: [
    { id: 'consequence.sfera.complete', trigger: 'success', summary: 'Анна принимает handoff и открывает самостоятельные контракты первой линии.', effects: { sferaTrust: 2, opensAct1Contracts: true } },
    { id: 'consequence.sfera.isolate', trigger: 'decision', decisionId: 'decision.sfera.isolate-preserve', summary: 'ACC-WS-07 уходит в изоляцию, сотруднику выдают резервное место.', effects: { downtime: 1, evidenceQuality: 2 } },
    { id: 'consequence.sfera.delete', trigger: 'critical-error', summary: 'Удаление evidence блокирует завершение до reset.', effects: { requiresReset: true } },
  ],
  replay: { seeded: true, variables: ['user', 'host', 'sender-domain', 'beacon-domain', 'pid', 'event-order', 'noise'] },
  safety: { sandboxed: true, externalNetwork: false, allowedActions: ['open-local-alert', 'read-local-artifact', 'filter-local-telemetry', 'link-evidence', 'submit-local-report'], resettable: true },
};
